import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { useAppLayoutNavbarSurface } from '../queries/useAppLayoutNavbarSurface'

describe('AppNavbar boundary', () => {
	it('keeps layout navigation reusable and slot-based', () => {
		const source = readFileSync(new URL('./AppNavbar.vue', import.meta.url), 'utf8')
		const layoutCss = readFileSync(new URL('./app-layout.css', import.meta.url), 'utf8')

		expect(source).toContain('<slot name="page-actions"')
		expect(source).toContain('breadcrumbs?: readonly AppNavbarBreadcrumb[]')
		expect(source).toContain('navigationLevels?: readonly AppNavbarNavigationLevel[]')
			expect(source).toContain('healthChecks?: readonly AppNavbarHealthCheck[]')
			expect(source).toContain('languageOptions?: AppNavbarToggleOption[]')
			expect(source).toContain('notifications?: readonly AppNavbarNotification[]')
			expect(source).toContain('themeFamilyOptions?: AppNavbarThemeFamilyOption[]')
			expect(source).toContain('themeModeOptions?: AppNavbarThemeModeOption[]')
			expect(source).toContain('notificationsCount?: number')
			expect(source).toContain('healthStatusLabelVisibleMs?: number')
		expect(source).toContain("function handleBrandClick(): void")
		expect(source).toContain("emit('navigationSelect', 'dashboard')")
		expect(source).toContain("function handleSettingsClick(): void")
		expect(source).toContain("emit('navigationSelect', 'settings')")
		expect(source).toContain('aria-label="Dashboard"')
		expect(source).toContain('class="app-navbar__brand"')
		expect(source).toContain('@click="handleBrandClick"')
		expect(source).toContain('src="/assets/hermes-logo-mark-light.png"')
		expect(source).toContain('src="/assets/hermes-logo-mark-dark.png"')
		expect(source).toContain('app-navbar__brand-logo--light')
		expect(source).toContain('app-navbar__brand-logo--dark')
			expect(source.indexOf('class="app-navbar__brand"')).toBeLessThan(source.indexOf('<AppNavbarRouteBreadcrumbs'))
			expect(layoutCss).not.toContain('.app-navbar__brand:hover')
			expect(layoutCss).toContain('.app-navbar__brand:focus-visible')
			expect(layoutCss).toContain("[data-ui-theme-mode='light'] .app-navbar__brand-logo--light")
			expect(layoutCss).toContain("[data-ui-theme-mode='dark'] .app-navbar__brand-logo--light")
			expect(layoutCss).toContain("[data-ui-theme-mode='dark'] .app-navbar__brand-logo--dark")
			expect(layoutCss).toContain(".app-navbar__brand-logo--dark")
			expect(layoutCss).toContain('.app-navbar__health-button--label-visible')
		expect(layoutCss).toContain('max-width: 0')
		expect(layoutCss).toContain('max-width var(--app-navbar-health-motion)')
		expect(source).toContain("import Drawer from '../../shared/ui/Drawer.vue'")
		expect(source).toContain("import AppNavbarRouteBreadcrumbs from './AppNavbarRouteBreadcrumbs.vue'")
		expect(source).toContain("import { useMouseLeaveDismiss } from '../../shared/ui/useMouseLeaveDismiss'")
		expect(source).not.toContain('useNavigationStore')
		expect(source).not.toContain('useNotificationsStore')
		expect(source).not.toContain('useRealtimeStatusStore')
		expect(source).not.toContain('useTopbarSurface')
	})

	it('exposes the requested system and user menu controls', () => {
		const source = readFileSync(new URL('./AppNavbar.vue', import.meta.url), 'utf8')

		expect(source).toContain('System health checks')
		expect(source).toContain('<AppNavbarRouteBreadcrumbs')
		expect(source).toContain('@select="handleNavigationSelect"')
		expect(source).toContain('tabler:heartbeat')
		expect(source).toContain('tabler:bell')
		expect(source).toContain('title="Уведомления"')
		expect(source).toContain('side="right"')
		expect(source).toContain('Список уведомлений')
		expect(source).toContain('visibleNotifications')
		expect(source).toContain("import ToggleGroup from '../../shared/ui/ToggleGroup.vue'")
		expect(source).toContain('hermes-toggle-group--tabs')
			expect(source).toContain('Смена языка')
			expect(source).toContain('Смена темы')
			expect(source).toContain('Семейство темы')
			expect(source).toContain('Вариант темы')
			expect(source).toContain('aria-haspopup="listbox"')
			expect(source).toContain('role="option"')
		expect(source).toContain('@mouseleave="scheduleUserMouseLeaveDismiss"')
		expect(source).toContain('@mouseleave="scheduleThemeMouseLeaveDismiss"')
		expect(source).toContain('@mouseenter="handleHealthPointerEnter"')
		expect(source).toContain('@mouseleave="handleHealthPointerLeave"')
		expect(source).toContain("watch(systemStatus")
		expect(source).toContain('revealHealthLabelTemporarily')
			expect(source).toContain('isHealthLabelVisible')
			expect(source).toContain('app-navbar__health-button--label-visible')
			expect(source).toContain('healthStatusLabelVisibleMs: 5000')
			expect(source).toContain(':aria-hidden="!isHealthLabelVisible"')
			expect(source).toContain("emit('themeFamilyChange'")
			expect(source).toContain("emit('themeModeChange'")
			expect(source).toContain('tabler:settings')
		expect(source).toContain('Настройки')
		expect(source).toContain('@click="handleSettingsClick"')
		expect(source).not.toContain(':href="settingsHref"')
		expect(source).toContain('Выход')
	})

	it('locks the app layout to the viewport and keeps scrolling inside panes', () => {
		const layoutCss = readFileSync(new URL('./app-layout.css', import.meta.url), 'utf8')

		expect(layoutCss).toContain('html,\nbody,\n#app')
		expect(layoutCss).toContain('overflow: hidden')
		expect(layoutCss).toContain('overscroll-behavior: none')
		expect(layoutCss).toContain('.app-layout-root')
		expect(layoutCss).toContain('position: relative')
		expect(layoutCss).toContain('display: block')
		expect(layoutCss).toContain('width: 100dvw')
		expect(layoutCss).toContain('height: 100dvh')
		expect(layoutCss).toContain('max-height: 100%')
		expect(layoutCss).toContain('.hermes-app-layout__main')
		expect(layoutCss).toContain('overflow: auto')
		expect(layoutCss).toContain('.hermes-app-layout__rail,\n.hermes-app-layout__sidebar,\n.hermes-app-layout__inspector')
	})

	it('mounts the navbar in the main AppLayout root', () => {
		const root = readFileSync(new URL('./AppLayoutRoot.vue', import.meta.url), 'utf8')
		const app = readFileSync(new URL('../App.vue', import.meta.url), 'utf8')
		const main = readFileSync(new URL('../../main.ts', import.meta.url), 'utf8')
		const appLayoutHtml = readFileSync(new URL('../../../app-layout.html', import.meta.url), 'utf8')
		const surface = readFileSync(new URL('../queries/useAppLayoutNavbarSurface.ts', import.meta.url), 'utf8')

		expect(app).toContain("import AppLayoutRoot from './layout/AppLayoutRoot.vue'")
		expect(app).toContain('<AppLayoutRoot />')
		expect(main).not.toContain("import router from './app/router'")
		expect(main).not.toContain('app.use(router)')
		expect(main).toContain("import './app/layout/app-layout.css'")
		expect(appLayoutHtml).toContain('<div id="app"></div>')
		expect(appLayoutHtml).toContain('src="/src/main.ts"')
		expect(root).toContain("import { useAppLayoutNavbarSurface } from '../queries/useAppLayoutNavbarSurface'")
		expect(root).toContain("import Toast from '../../shared/ui/Toast.vue'")
			expect(root).toContain("import AppNavbar from './AppNavbar.vue'")
			expect(root).toContain('const navbar = useAppLayoutNavbarSurface()')
			expect(root).toContain('const breadcrumbs = navbar.breadcrumbs')
			expect(root).toContain('const currentTheme = navbar.currentTheme')
			expect(root).toContain('const currentThemeFamily = navbar.currentThemeFamily')
			expect(root).toContain('const currentThemeMode = navbar.currentThemeMode')
			expect(root).toContain('const navigationLevels = navbar.navigationLevels')
			expect(root).toContain('const notificationToasts = navbar.notificationToasts')
			expect(root).toContain(':data-ui-theme="currentTheme"')
			expect(root).toContain(':data-ui-theme-family="currentThemeFamily"')
			expect(root).toContain(':data-ui-theme-mode="currentThemeMode"')
			expect(root).toContain("document.documentElement.setAttribute('data-ui-theme', theme)")
			expect(root).toContain("document.documentElement.setAttribute('data-ui-theme-family', family)")
			expect(root).toContain("document.documentElement.setAttribute('data-ui-theme-mode', mode)")
			expect(root).toContain('<Toast')
		expect(root).toContain('class="app-layout-notification-toasts"')
		expect(root).toContain('close-label="Закрыть уведомление"')
		expect(root).toContain(':default-toasts="notificationToasts"')
		expect(root).toContain(':duration="navbar.notificationToastVisibleMs"')
		expect(root).toContain('<template #topbar>')
		expect(root).toContain(':breadcrumbs="breadcrumbs"')
			expect(root).toContain(':health-checks="navbar.healthChecks"')
			expect(root).toContain(':health-status-label-visible-ms="navbar.healthStatusLabelVisibleMs"')
			expect(root).toContain(':language-options="navbar.languageOptions"')
			expect(root).toContain(':navigation-levels="navigationLevels"')
			expect(root).toContain(':notifications="navbar.notifications"')
			expect(root).toContain(':theme-family-options="navbar.themeFamilyOptions"')
			expect(root).toContain(':theme-mode-options="navbar.themeModeOptions"')
			expect(root).toContain('@theme-family-change="navbar.selectThemeFamily"')
			expect(root).toContain('@theme-mode-change="navbar.selectThemeMode"')
			expect(root).toContain(':notifications-count="navbar.notificationsCount"')
		expect(root).toContain('@navigation-select="navbar.selectNavigationItem"')
		expect(surface).toContain('Main menu')
		expect(surface).toContain('Sub menu')
		expect(surface).toContain('Elem')
		expect(surface).toContain('routeTree')
		expect(surface).toContain('Communication')
		expect(surface).toContain("selectedRouteId = ref('telegram-all-accounts')")
		expect(surface).toContain('communication-all-channels')
		expect(surface).toContain('All channels')
		expect(surface).toContain('telegram-all-accounts')
		expect(surface).toContain('mail-all-accounts')
		expect(surface).toContain('whatsapp-all-accounts')
		expect(surface).toContain('All accounts')
		expect(surface).toContain("iconTone: 'telegram'")
		expect(surface).toContain("iconTone: 'whatsapp'")
		expect(surface).toContain("iconTone: 'mail'")
		expect(surface).toContain("iconTone: 'communication'")
			expect(surface).toContain('Telegram account 1')
			expect(surface).toContain('Mail account 1')
			expect(surface).toContain('selectNavigationItem')
			expect(surface).toContain('Русский')
			expect(surface).toContain('English')
			expect(surface).toContain('currentTheme')
			expect(surface).toContain("currentThemeFamily = ref<UiThemeFamily>('base')")
			expect(surface).toContain("currentThemeMode = ref<UiThemeMode>('light')")
			expect(surface).toContain('themeSelectionToName(currentThemeFamily.value, currentThemeMode.value)')
			expect(surface).toContain('themeFamilyOptions')
			expect(surface).toContain('themeModeOptions')
			expect(surface).toContain('Light')
			expect(surface).toContain('Dark')
			expect(surface).toContain('Hermes')
		expect(surface).toContain('healthStatusLabelVisibleMs = 5000')
		expect(surface).toContain('healthStatusLabelVisibleMs')
		expect(surface).toContain('notificationToasts')
		expect(surface).toContain('notificationToastVisibleMs = 5000')
		expect(surface).toContain('notificationToneToToastVariant')
		expect(surface).toContain('Vault требует разблокировки')
		expect(surface).toContain('Review')
		expect(surface).toContain("id: 'settings'")
		expect(surface).toContain('notificationsCount: notifications.length')
	})

	it('models communication aggregate pages as selectable route leaves', () => {
		const surface = useAppLayoutNavbarSurface()

		expect(currentNavigationPath(surface)).toEqual(['Communication', 'Telegram', 'All accounts'])
		expect(levelOptions(surface, 'Sub menu')).toEqual(['All channels', 'Telegram', 'Mail', 'WhatsApp'])
		expect(levelOptions(surface, 'Elem')).toEqual(['All accounts', 'Telegram account 1', 'Telegram account 2'])

		surface.selectNavigationItem('communications')
		expect(currentNavigationPath(surface)).toEqual(['Communication', 'All channels'])

		surface.selectNavigationItem('mail')
		expect(currentNavigationPath(surface)).toEqual(['Communication', 'Mail', 'All accounts'])
		expect(levelOptions(surface, 'Elem')).toEqual(['All accounts', 'Mail account 1', 'Mail account 2'])

		surface.selectNavigationItem('whatsapp')
		expect(currentNavigationPath(surface)).toEqual(['Communication', 'WhatsApp', 'All accounts'])
		expect(levelOptions(surface, 'Elem')).toEqual(['All accounts', 'WhatsApp account 1', 'WhatsApp account 2'])
	})

	it('prepares app notifications for the toast host', () => {
		const surface = useAppLayoutNavbarSurface()

		expect(surface.notificationToastVisibleMs).toBe(5000)
		expect(surface.notificationToasts.value.map((toast) => toast.variant)).toEqual(['warning', 'info', 'success'])
		expect(surface.notificationToasts.value.map((toast) => toast.id)).toEqual([
			'vault-unlock-required',
			'review-candidates-ready',
			'event-spine-connected'
		])
	})

	it('maps navbar theme family and mode to explicit runtime ids', () => {
		const surface = useAppLayoutNavbarSurface()

		expect(surface.currentTheme.value).toBe('base-light')
		expect(surface.themeFamilyOptions.map((option) => option.value)).toEqual(['base', 'hermes'])
		expect(surface.themeModeOptions.map((option) => option.value)).toEqual(['light', 'dark'])

		surface.selectThemeMode('dark')
		expect(surface.currentTheme.value).toBe('base-dark')

		surface.selectThemeFamily('hermes')
		expect(surface.currentTheme.value).toBe('hermes-dark')

		surface.selectThemeMode('light')
		expect(surface.currentTheme.value).toBe('hermes-light')

		surface.selectThemeFamily('base')
		expect(surface.currentTheme.value).toBe('base-light')
		surface.selectThemeFamily('hermes')
		surface.selectThemeMode('dark')
		surface.selectThemeFamily('light')
		surface.selectThemeMode('hermes')
		expect(surface.currentTheme.value).toBe('hermes-dark')
	})
})

type AppLayoutNavbarSurface = ReturnType<typeof useAppLayoutNavbarSurface>

function currentNavigationPath(surface: AppLayoutNavbarSurface): string[] {
	return surface.navigationLevels.value.map((level) => level.currentItem.label)
}

function levelOptions(surface: AppLayoutNavbarSurface, label: string): string[] {
	return surface.navigationLevels.value.find((level) => level.label === label)?.items.map((item) => item.label) ?? []
}
