import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

describe('TelegramThreadSideSections media boundary', () => {
  it('renders voice/media download surfaces without inline fetches', () => {
    const source = readFileSync(new URL('./TelegramThreadSideSections.vue', import.meta.url), 'utf8')

    expect(source).toContain("activeThreadTab === 'voice'")
    expect(source).toContain('voiceHints: TelegramAttachmentHint[]')
    expect(source).toContain('mergeTelegramAttachmentHints(props.mediaGalleryItems, props.fileHints)')
    expect(source).toContain('telegramMediaAlbumGroupsForMessages(props.chronologicalMessages)')
    expect(source).toContain('telegram-media-album-card')
    expect(source).toContain('TelegramAttachmentSearchPanel')
    expect(source).toContain('TelegramDownloadQueueStatus')
    expect(source).toContain('accountId: string | null | undefined')
    expect(source).toContain('<TelegramAttachmentSearchPanel :accountId="accountId" />')
    expect(source).toContain(':fileHints="mergedFileHints"')
    expect(source).toContain(':voiceHints="voiceHints"')
    expect(source).toContain("t('Media album')")
    expect(source).toContain('attachmentIcon(attachment)')
    expect(source).toContain("attachment.kind === 'sticker'")
    expect(source).toContain("attachment.kind === 'animation' || attachment.kind === 'video_note'")
    expect(source).toContain('telegramAttachmentReadiness')
    expect(source).toContain('attachmentReadiness(attachment).detail')
    expect(source).toContain('attachmentReadiness(voice).action_label')
    expect(source).toContain('telegram-voice-card__player')
    expect(source).toContain("emit('downloadMedia', attachment, messageForAttachment(attachment) ?? undefined)")
    expect(source).toContain("@downloadMedia=\"(attachment) => emit('downloadMedia', attachment, messageForAttachment(attachment) ?? undefined)\"")
    expect(source).toContain("t('Voice playback is available after local download.')")
    expect(source).toContain("emit('downloadMedia', voice, messageForAttachment(voice) ?? undefined)")
    expect(source).toContain("activeThreadTab === 'topics'")
    expect(source).toContain('TelegramThreadTopicsPanel')
    expect(source).not.toContain('fetch(')
  })
})

describe('TelegramThreadTopicsPanel boundary', () => {
  it('owns topic lifecycle controls through query/mutation hooks without inline fetches', () => {
    const source = readFileSync(new URL('./TelegramThreadTopicsPanel.vue', import.meta.url), 'utf8')

    expect(source).toContain('useCreateTelegramTopicMutation')
    expect(source).toContain('useToggleTelegramTopicClosedMutation')
    expect(source).toContain('useTelegramAccountCapabilitiesQuery')
    expect(source).toContain('telegramTopicStateLabel')
    expect(source).toContain('telegramTopicProviderLabel')
    expect(source).toContain('newTopicTitle')
    expect(source).toContain('submitTopicCreate')
    expect(source).toContain('toggleTopicClosed')
    expect(source).toContain('telegram-topic-toolbar')
    expect(source).toContain("t('Create topic')")
    expect(source).toContain("t('Close topic')")
    expect(source).toContain("t('Reopen topic')")
    expect(source).toContain('telegram-topic-card__action')
    expect(source).not.toContain('fetch(')
  })
})
