use super::support::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/api/v1/calendar/accounts",
            get(get_calendar_accounts).post(post_calendar_account),
        )
        .route(
            "/api/v1/calendar/accounts/{account_id}",
            get(get_calendar_account)
                .put(put_calendar_account)
                .delete(delete_calendar_account),
        )
        .route(
            "/api/v1/calendar/accounts/{account_id}/sources",
            get(get_calendar_sources).post(post_calendar_source),
        )
        .route(
            "/api/v1/calendar/events",
            get(get_calendar_events).post(post_calendar_event),
        )
        .route(
            "/api/v1/calendar/events/{event_id}",
            get(get_calendar_event)
                .put(put_calendar_event)
                .delete(delete_calendar_event),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/reschedule",
            post(post_calendar_event_reschedule),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/cancel",
            post(post_calendar_event_cancel),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/participants",
            get(get_event_participants).post(post_event_participant),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/relations",
            get(get_event_relations).post(post_event_relation),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/context-pack",
            get(get_event_context_pack).post(post_event_context_pack),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/agenda",
            get(get_event_agenda).post(post_event_agenda),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/checklist",
            get(get_event_checklist).post(post_event_checklist),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/classify",
            post(post_event_classify),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/analyze",
            post(post_event_analyze),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/risks",
            get(get_event_risks),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/notes",
            get(get_meeting_notes).post(post_meeting_note),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/outcomes",
            get(get_meeting_outcomes).post(post_meeting_outcome),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/recording",
            get(get_event_recordings).post(post_event_recording),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/transcript",
            get(get_event_transcript),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/follow-up",
            post(post_event_follow_up),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/follow-up-status",
            get(get_event_follow_up_status),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/brief",
            get(get_event_brief),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/generate-agenda",
            post(post_generate_agenda),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/export",
            get(get_event_export),
        )
        .route(
            "/api/v1/calendar/deadlines",
            get(get_deadlines).post(post_deadline),
        )
        .route(
            "/api/v1/calendar/focus-blocks",
            get(get_focus_blocks).post(post_focus_block),
        )
        .route("/api/v1/calendar/smart-schedule", post(post_smart_schedule))
        .route("/api/v1/calendar/watchtower", get(get_calendar_watchtower))
        .route("/api/v1/calendar/health", get(get_calendar_health))
        .route("/api/v1/calendar/weekly-brief", get(get_weekly_brief))
        .route("/api/v1/calendar/analytics", get(get_calendar_analytics))
        .route("/api/v1/calendar/brain", post(post_calendar_brain))
        .route("/api/v1/calendar/search", get(get_calendar_search))
        .route(
            "/api/v1/calendar/rules",
            get(get_calendar_rules).post(post_calendar_rule),
        )
        .route(
            "/api/v1/calendar/rules/{rule_id}",
            put(put_calendar_rule).delete(delete_calendar_rule),
        )
        .route("/api/v1/calendar/import", post(post_calendar_import))
        .route(
            "/api/v1/calendar/accounts/{account_id}/sync",
            post(post_calendar_sync),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/reminders",
            get(get_event_reminders).post(post_event_reminder),
        )
        .route(
            "/api/v1/calendar/events/{event_id}/reminders/{reminder_id}/toggle",
            post(post_event_reminder_toggle),
        )
        .route(
            "/api/v1/calendar/analytics/distribution",
            get(get_time_distribution),
        )
        .route(
            "/api/v1/calendar/analytics/focus-balance",
            get(get_focus_balance),
        )
        .route(
            "/api/v1/calendar/analytics/back-to-back",
            get(get_back_to_back),
        )
}
