use super::support::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/api/v1/communications/messages",
            get(get_v1_communication_messages),
        )
        .route(
            "/api/v1/communications/messages/{message_id}",
            get(get_v1_communication_message),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/workflow-state",
            put(put_v1_message_workflow_state),
        )
        .route(
            "/api/v1/communications/messages/states",
            get(get_v1_message_workflow_state_counts),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/analyze",
            post(post_v1_message_analyze),
        )
        .route("/api/v1/workflow-actions", post(post_v1_workflow_action))
        .route("/api/v1/communications/threads", get(get_v1_threads))
        .route(
            "/api/v1/communications/threads/messages",
            get(get_v1_thread_messages),
        )
        .route("/api/v1/communications/search", get(get_v1_email_search))
        .route(
            "/api/v1/communications/personas",
            get(get_v1_personas).post(post_v1_persona),
        )
        .route(
            "/api/v1/communications/drafts",
            get(get_v1_drafts).post(post_v1_draft),
        )
        .route(
            "/api/v1/communications/drafts/{draft_id}",
            get(get_v1_draft).delete(delete_v1_draft),
        )
        .route(
            "/api/v1/communications/finance/invoices",
            get(get_v1_invoices).post(post_v1_invoice),
        )
        .route(
            "/api/v1/communications/analytics/health",
            get(get_v1_analytics_health),
        )
        .route(
            "/api/v1/communications/analytics/senders",
            get(get_v1_analytics_senders),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/explain",
            get(get_v1_message_explain),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/smart-cc",
            get(get_v1_message_smart_cc),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/pin",
            post(post_v1_message_pin),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/important",
            post(post_v1_message_important),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/snooze",
            post(post_v1_message_snooze),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/mute",
            post(post_v1_message_mute),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/labels",
            post(post_v1_message_label).delete(delete_v1_message_label),
        )
        .route(
            "/api/v1/communications/subscriptions",
            get(get_v1_subscriptions),
        )
        .route(
            "/api/v1/communications/attachments/duplicates",
            get(get_v1_attachment_duplicates),
        )
        .route(
            "/api/v1/communications/legal",
            get(get_v1_legal_docs).post(post_v1_legal_doc),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/export",
            get(get_v1_message_export),
        )
        .route("/api/v1/communications/send", post(post_v1_send))
        .route(
            "/api/v1/communications/messages/{message_id}/reply",
            post(post_v1_reply),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/imap-mark-read",
            post(post_v1_imap_mark_read),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/imap-delete",
            post(post_v1_imap_delete),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/trash",
            post(post_v1_message_trash),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/restore",
            post(post_v1_message_restore),
        )
        .route(
            "/api/v1/communications/certificates",
            get(get_v1_certs).post(post_v1_cert),
        )
        .route(
            "/api/v1/communications/certificates/expiring",
            get(get_v1_certs_expiring),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/signature",
            get(get_v1_signature_check),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/forward",
            post(post_v1_forward),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/detect-language",
            get(get_v1_detect_language),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/translate",
            post(post_v1_translate),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/ai-reply",
            post(post_v1_ai_reply),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/ai-reply-variants",
            post(post_v1_ai_reply_variants),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/reply-all",
            post(post_v1_reply_all),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/forward-eml",
            post(post_v1_forward_eml),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/spf-dkim",
            get(get_v1_spf_dkim),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/extract-tasks",
            post(post_v1_extract_tasks),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/extract-notes",
            post(post_v1_extract_notes),
        )
        .route(
            "/api/v1/communications/templates/rich",
            get(get_v1_rich_templates).post(post_v1_rich_template),
        )
        .route(
            "/api/v1/communications/templates/rich/render",
            post(post_v1_render_template),
        )
        .route("/api/v1/communications/blockers", get(get_v1_blockers))
}
