use super::support::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/api/v1/integrations/telegram/capabilities",
            get(get_telegram_capabilities),
        )
        .route(
            "/api/v1/integrations/whatsapp/capabilities",
            get(get_whatsapp_capabilities),
        )
        .route(
            "/api/v1/integrations/zoom/capabilities",
            get(get_zoom_capabilities),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/capabilities",
            get(get_yandex_telemost_capabilities),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/accounts",
            get(get_yandex_telemost_accounts).post(post_yandex_telemost_account),
        )
        .route(
            "/api/v1/integrations/zulip/accounts",
            post(post_zulip_account),
        )
        .route(
            "/api/v1/integrations/zulip/accounts/{account_id}/commands/stream-upload",
            post(post_zulip_stream_upload_command),
        )
        .route(
            "/api/v1/integrations/zulip/accounts/{account_id}/commands/direct-upload",
            post(post_zulip_direct_upload_command),
        )
        .route(
            "/api/v1/integrations/zulip/accounts/{account_id}/commands/upload",
            post(post_zulip_upload_command),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/runtime/status",
            get(get_yandex_telemost_runtime_status),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/accounts/{account_id}/retention/prune",
            post(post_yandex_telemost_retention_cleanup),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/conferences",
            post(post_yandex_telemost_conference),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/conferences/{account_id}/{conference_id}",
            get(get_yandex_telemost_conference).patch(patch_yandex_telemost_conference),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/conferences/{account_id}/{conference_id}/cohosts",
            get(get_yandex_telemost_cohosts),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/webview/manifest",
            post(post_yandex_telemost_webview_manifest),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/recording/intent",
            post(post_yandex_telemost_recording_intent),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/runtime-bridge/recordings",
            post(post_yandex_telemost_runtime_bridge_recording),
        )
        .route(
            "/api/v1/integrations/yandex-telemost/runtime-bridge/transcripts",
            post(post_yandex_telemost_runtime_bridge_transcript),
        )
        .route(
            "/api/v1/integrations/zoom/accounts",
            get(get_zoom_accounts).post(post_zoom_account),
        )
        .route(
            "/api/v1/integrations/zoom/oauth/start",
            post(post_zoom_oauth_start),
        )
        .route(
            "/api/v1/integrations/zoom/oauth/complete",
            post(post_zoom_oauth_complete),
        )
        .route(
            "/api/v1/integrations/zoom/oauth/server-to-server/authorize",
            post(post_zoom_server_to_server_authorize),
        )
        .route(
            "/api/v1/integrations/zoom/oauth/refresh",
            post(post_zoom_oauth_refresh),
        )
        .route(
            "/api/v1/integrations/zoom/oauth/maintenance",
            post(post_zoom_oauth_maintenance),
        )
        .route(
            "/api/v1/integrations/zoom/provider-sync/recordings",
            post(post_zoom_provider_sync_recordings),
        )
        .route(
            "/api/v1/integrations/zoom/webhook-subscriptions/status",
            get(get_zoom_webhook_subscription_status),
        )
        .route(
            "/api/v1/integrations/zoom/webhook-subscriptions/reconcile",
            post(post_zoom_webhook_subscription_reconcile),
        )
        .route(
            "/api/v1/integrations/zoom/webhook-subscriptions/remove",
            post(post_zoom_webhook_subscription_remove),
        )
        .route(
            "/api/v1/integrations/zoom/accounts/{account_id}/runtime/status",
            get(get_zoom_account_runtime_status),
        )
        .route(
            "/api/v1/integrations/zoom/accounts/{account_id}/recording-imports",
            get(get_zoom_recording_imports),
        )
        .route(
            "/api/v1/integrations/zoom/accounts/{account_id}/recording-imports/{attachment_id}/remove",
            post(post_zoom_recording_import_remove),
        )
        .route(
            "/api/v1/integrations/zoom/accounts/{account_id}/audit-events",
            get(get_zoom_audit_events),
        )
        .route(
            "/api/v1/integrations/zoom/accounts/{account_id}/retention/prune",
            post(post_zoom_retention_cleanup),
        )
        .route(
            "/api/v1/integrations/zoom/runtime/status",
            get(get_zoom_runtime_status),
        )
        .route(
            "/api/v1/integrations/zoom/runtime/start",
            post(post_zoom_runtime_start),
        )
        .route(
            "/api/v1/integrations/zoom/runtime/stop",
            post(post_zoom_runtime_stop),
        )
        .route(
            "/api/v1/integrations/zoom/runtime/remove",
            post(post_zoom_runtime_remove),
        )
        .route(
            "/api/v1/integrations/zoom/runtime-bridge/meetings",
            post(post_zoom_runtime_bridge_meeting),
        )
        .route(
            "/api/v1/integrations/zoom/runtime-bridge/recordings",
            post(post_zoom_runtime_bridge_recording),
        )
        .route(
            "/api/v1/integrations/zoom/runtime-bridge/transcripts",
            post(post_zoom_runtime_bridge_transcript),
        )
        .route(
            "/api/v1/integrations/zoom/runtime-bridge/transcript-files",
            post(post_zoom_runtime_bridge_transcript_file),
        )
        .route(
            "/api/v1/integrations/zoom/runtime-bridge/webhooks",
            post(post_zoom_runtime_bridge_webhook),
        )
        .route(
            "/api/v1/integrations/zoom/fixtures/accounts",
            post(post_zoom_fixture_account),
        )
        .route(
            "/api/v1/integrations/whatsapp/accounts/{account_id}/capabilities",
            get(get_whatsapp_account_capabilities),
        )
        .route(
            "/api/v1/integrations/whatsapp/accounts",
            get(get_whatsapp_accounts).post(post_whatsapp_account),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/status",
            get(get_whatsapp_runtime_status),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/start",
            post(post_whatsapp_runtime_start),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/stop",
            post(post_whatsapp_runtime_stop),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/revoke",
            post(post_whatsapp_runtime_revoke),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/relink",
            post(post_whatsapp_runtime_relink),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/rotate",
            post(post_whatsapp_runtime_rotate),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/remove",
            post(post_whatsapp_runtime_remove),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/health",
            get(get_whatsapp_runtime_health),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/messages",
            post(post_whatsapp_runtime_bridge_message),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/message-updates",
            post(post_whatsapp_runtime_bridge_message_update),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/message-deletes",
            post(post_whatsapp_runtime_bridge_message_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/receipts",
            post(post_whatsapp_runtime_bridge_receipt),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/business-cloud/webhooks",
            get(get_whatsapp_runtime_bridge_business_cloud_webhook)
                .post(post_whatsapp_runtime_bridge_business_cloud_webhook),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/business-cloud/proxy-manifest",
            get(get_whatsapp_runtime_bridge_business_cloud_proxy_manifest),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/dialogs",
            post(post_whatsapp_runtime_bridge_dialog),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/participants",
            post(post_whatsapp_runtime_bridge_participant),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/reactions",
            post(post_whatsapp_runtime_bridge_reaction),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/media",
            post(post_whatsapp_runtime_bridge_media),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/media-lifecycle",
            post(post_whatsapp_runtime_bridge_media_lifecycle),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/statuses",
            post(post_whatsapp_runtime_bridge_status),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/status-views",
            post(post_whatsapp_runtime_bridge_status_view),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/status-deletes",
            post(post_whatsapp_runtime_bridge_status_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/presence",
            post(post_whatsapp_runtime_bridge_presence),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/calls",
            post(post_whatsapp_runtime_bridge_call),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/runtime-events",
            post(post_whatsapp_runtime_bridge_runtime_event),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/sync-lifecycle",
            post(post_whatsapp_runtime_bridge_sync_lifecycle),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/commands/claim",
            post(post_whatsapp_runtime_bridge_claim_commands),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/commands/{command_id}/failed",
            post(post_whatsapp_runtime_bridge_command_failed),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/sessions/authorized",
            post(post_whatsapp_runtime_bridge_authorized_session),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/chats",
            post(post_whatsapp_sync_chats),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/history",
            post(post_whatsapp_sync_history),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/conversations/{provider_chat_id}/members",
            post(post_whatsapp_sync_members),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/statuses",
            post(post_whatsapp_sync_statuses),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/presence",
            post(post_whatsapp_sync_presence),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/calls",
            post(post_whatsapp_sync_calls),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/contacts",
            post(post_whatsapp_sync_contacts),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/media",
            post(post_whatsapp_sync_media),
        )
        .route(
            "/api/v1/integrations/whatsapp/login/qr/start",
            post(post_whatsapp_qr_link_start),
        )
        .route(
            "/api/v1/integrations/whatsapp/login/pair-code/start",
            post(post_whatsapp_pair_code_link_start),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/send",
            post(post_whatsapp_command_send_text),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/reply",
            post(post_whatsapp_command_reply),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/forward",
            post(post_whatsapp_command_forward),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/edit",
            post(post_whatsapp_command_edit),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/delete",
            post(post_whatsapp_command_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/reactions",
            post(post_whatsapp_command_react).delete(delete_whatsapp_command_react),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-media/upload",
            post(post_whatsapp_media_upload),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-media/download",
            post(post_whatsapp_media_download),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/voice-note",
            post(post_whatsapp_voice_note_send),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/statuses/publish",
            post(post_whatsapp_status_publish),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/join",
            post(post_whatsapp_conversation_join_group),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/read",
            post(post_whatsapp_conversation_mark_read),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unread",
            post(post_whatsapp_conversation_mark_unread),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/archive",
            post(post_whatsapp_conversation_archive),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unarchive",
            post(post_whatsapp_conversation_unarchive),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/mute",
            post(post_whatsapp_conversation_mute),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unmute",
            post(post_whatsapp_conversation_unmute),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/pin",
            post(post_whatsapp_conversation_pin),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unpin",
            post(post_whatsapp_conversation_unpin),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/leave",
            post(post_whatsapp_conversation_leave_group),
        )
        .route(
            "/api/v1/integrations/whatsapp/commands",
            get(get_whatsapp_commands),
        )
        .route(
            "/api/v1/integrations/whatsapp/commands/{command_id}/retry",
            post(post_whatsapp_command_retry),
        )
        .route(
            "/api/v1/integrations/whatsapp/commands/{command_id}/dead-letter",
            post(post_whatsapp_command_dead_letter),
        )
        .route("/api/v1/integrations/telegram/fixtures/accounts", post(post_telegram_fixture_account))
        .route(
            "/api/v1/integrations/telegram/accounts",
            get(get_telegram_accounts).post(post_telegram_account),
        )
        .route(
            "/api/v1/integrations/telegram/accounts/{account_id}/capabilities",
            get(get_telegram_account_capabilities),
        )
        .route(
            "/api/v1/integrations/telegram/accounts/{account_id}",
            delete(delete_telegram_account),
        )
        .route(
            "/api/v1/integrations/telegram/accounts/{account_id}/logout",
            post(post_telegram_account_logout),
        )
        .route(
            "/api/v1/integrations/telegram/runtime/status",
            get(get_telegram_runtime_status),
        )
        .route(
            "/api/v1/integrations/telegram/runtime/start",
            post(post_telegram_runtime_start),
        )
        .route(
            "/api/v1/integrations/telegram/runtime/stop",
            post(post_telegram_runtime_stop),
        )
        .route(
            "/api/v1/integrations/telegram/runtime/restart",
            post(post_telegram_runtime_restart),
        )
        .route(
            "/api/v1/integrations/telegram/login/qr/start",
            post(post_telegram_qr_login_start),
        )
        .route(
            "/api/v1/integrations/telegram/login/qr/{setup_id}",
            get(get_telegram_qr_login_status).delete(delete_telegram_qr_login),
        )
        .route(
            "/api/v1/integrations/telegram/login/qr/{setup_id}/password",
            post(post_telegram_qr_login_password),
        )
        .route("/api/v1/communications/conversations", get(get_telegram_chats))
        .route(
            "/api/v1/communications/conversation-folders",
            get(get_telegram_folders),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/join",
            post(post_telegram_chat_join),
        )
        .route("/api/v1/integrations/telegram/conversation-folders", get(get_telegram_folders))
        .route(
            "/api/v1/communications/conversations/search",
            get(search_telegram_chats),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}",
            get(get_telegram_chat_detail),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/members",
            get(get_telegram_chat_members),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/messages",
            post(post_communication_conversation_message),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/read",
            post(post_communication_conversation_mark_read),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/unread",
            post(post_communication_conversation_mark_unread),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/pin",
            post(post_communication_conversation_pin),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/unpin",
            post(post_communication_conversation_unpin),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/archive",
            post(post_communication_conversation_archive),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/unarchive",
            post(post_communication_conversation_unarchive),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/mute",
            post(post_communication_conversation_mute),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/unmute",
            post(post_communication_conversation_unmute),
        )
        .route(
            "/api/v1/integrations/telegram/provider-sync/conversations/{telegram_chat_id}/members",
            post(post_telegram_chat_members_sync),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/pinned-messages",
            get(get_telegram_pinned_messages),
        )
        .route(
            "/api/v1/integrations/telegram/provider-sync/chats",
            post(post_telegram_sync_chats),
        )
        .route(
            "/api/v1/communications/search/messages",
            get(search_telegram_messages),
        )
        .route(
            "/api/v1/integrations/telegram/provider-search",
            post(post_telegram_provider_search),
        )
        .route("/api/v1/communications/search/media", get(search_telegram_media))
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/pin",
            post(post_telegram_chat_pin),
        )
        .route(
            "/api/v1/communications/conversations/{telegram_chat_id}/history-policy",
            put(put_telegram_chat_history_policy),
        )
        .route(
            "/api/v1/communications/conversations/{telegram_chat_id}/read-receipt-policy",
            put(put_telegram_chat_read_receipt_policy),
        )
        .route(
            "/api/v1/communications/conversations/{telegram_chat_id}/unread-counter-policy",
            put(put_telegram_chat_unread_counter_policy),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/unpin",
            post(post_telegram_chat_unpin),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/archive",
            post(post_telegram_chat_archive),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/unarchive",
            post(post_telegram_chat_unarchive),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/mute",
            post(post_telegram_chat_mute),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/folders/{provider_folder_id}",
            post(post_telegram_chat_add_folder),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/folders/{provider_folder_id}/remove",
            post(post_telegram_chat_remove_folder),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/folders/reassign",
            post(post_telegram_chat_reassign_folders),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/unmute",
            post(post_telegram_chat_unmute),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/read",
            post(post_telegram_chat_mark_read),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/unread",
            post(post_telegram_chat_mark_unread),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/conversations/{telegram_chat_id}/leave",
            post(post_telegram_chat_leave),
        )
        .route(
            "/api/v1/integrations/telegram/provider-sync/history",
            post(post_telegram_sync_history),
        )
        .route(
            "/api/v1/communications/conversations/{telegram_chat_id}/avatar",
            get(get_telegram_chat_avatar).post(post_telegram_chat_avatar_sync),
        )
        .route(
            "/api/v1/integrations/telegram/fixtures/messages",
            post(post_telegram_fixture_message),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/send",
            post(post_telegram_manual_send),
        )
        .route(
            "/api/v1/integrations/telegram/provider-media/download",
            post(post_telegram_media_download),
        )
        .route(
            "/api/v1/integrations/telegram/provider-media/upload",
            post(post_telegram_media_upload),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/edit",
            post(post_telegram_message_edit),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/{message_id}/edit",
            post(post_telegram_message_edit),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/delete",
            post(post_telegram_message_delete),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/{message_id}/delete",
            post(post_telegram_message_delete),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/restore-visibility",
            post(post_telegram_message_restore_visibility),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/{message_id}/restore-visibility",
            post(post_telegram_message_restore_visibility),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/{message_id}/reply",
            post(post_telegram_message_reply),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/{message_id}/forward",
            post(post_telegram_message_forward),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/{message_id}/pin",
            post(post_telegram_message_pin),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/mark-read",
            post(post_telegram_message_mark_read),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/messages/{message_id}/mark-read",
            post(post_telegram_message_mark_read),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/versions",
            get(get_telegram_message_versions),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/raw-evidence",
            get(get_telegram_message_raw),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/tombstones",
            get(get_telegram_message_tombstones),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/reply-chain",
            get(get_telegram_reply_chain),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/forward-chain",
            get(get_telegram_forward_chain),
        )
        .route(
            "/api/v1/communications/messages/{message_id}/reactions",
            get(get_telegram_reactions)
                .post(post_telegram_reaction)
                .delete(delete_telegram_reaction),
        )
        .route("/api/v1/integrations/telegram/commands", get(get_telegram_commands))
        .route(
            "/api/v1/integrations/telegram/commands/{command_id}/retry",
            post(post_telegram_command_retry),
        )
        .route(
            "/api/v1/communications/conversations/{conversation_id}/topics",
            get(get_telegram_topics).post(post_telegram_topic_create),
        )
        .route(
            "/api/v1/communications/topics/search",
            get(search_telegram_topics),
        )
        .route(
            "/api/v1/communications/topics/{topic_id}",
            get(get_telegram_topic_detail),
        )
        .route(
            "/api/v1/communications/topics/{topic_id}/close",
            post(post_telegram_topic_close),
        )
        .route(
            "/api/v1/integrations/telegram/provider-commands/topics/{topic_id}/close",
            post(post_telegram_topic_close),
        )
        .route(
            "/api/v1/communications/topics/{topic_id}/messages",
            get(get_telegram_topic_messages),
        )
        .route(
            "/api/v1/policies/templates",
            get(get_policy_templates).post(post_policy_template),
        )
        .route("/api/v1/policies", get(get_policies).post(post_policy))
        .route(
            "/api/v1/policies/telegram-send/dry-run",
            post(post_telegram_send_dry_run),
        )
        .route("/api/v1/calls", get(get_calls).post(post_call))
        .route(
            "/api/v1/calls/{call_id}/transcript",
            get(get_call_transcript).post(post_call_transcript_fixture),
        )
        .route("/api/v1/integrations/whatsapp/fixtures/accounts", post(post_whatsapp_fixture_account))
        .route("/api/v1/integrations/whatsapp/sessions", get(get_whatsapp_sessions))
        .route(
            "/api/v1/integrations/whatsapp/fixtures/messages",
            post(post_whatsapp_fixture_message),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/message-updates",
            post(post_whatsapp_fixture_message_update),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/message-deletes",
            post(post_whatsapp_fixture_message_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/receipts",
            post(post_whatsapp_fixture_receipt),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/dialogs",
            post(post_whatsapp_fixture_dialog),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/participants",
            post(post_whatsapp_fixture_participant),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/reactions",
            post(post_whatsapp_fixture_reaction),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/media",
            post(post_whatsapp_fixture_media),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/statuses",
            post(post_whatsapp_fixture_status),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/status-views",
            post(post_whatsapp_fixture_status_view),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/status-deletes",
            post(post_whatsapp_fixture_status_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/presence",
            post(post_whatsapp_fixture_presence),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/calls",
            post(post_whatsapp_fixture_call),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/runtime-events",
            post(post_whatsapp_fixture_runtime_event),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/sessions/authorized",
            post(post_whatsapp_fixture_authorized_session),
        )
}
