use super::support::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/api/v1/telegram/capabilities",
            get(get_telegram_capabilities),
        )
        .route(
            "/api/v1/whatsapp/capabilities",
            get(get_whatsapp_capabilities),
        )
        .route(
            "/api/v1/telegram/accounts/fixture",
            post(post_telegram_fixture_account),
        )
        .route(
            "/api/v1/telegram/accounts",
            get(get_telegram_accounts).post(post_telegram_account),
        )
        .route(
            "/api/v1/telegram/accounts/{account_id}",
            delete(delete_telegram_account),
        )
        .route(
            "/api/v1/telegram/accounts/{account_id}/logout",
            post(post_telegram_account_logout),
        )
        .route(
            "/api/v1/telegram/runtime/status",
            get(get_telegram_runtime_status),
        )
        .route(
            "/api/v1/telegram/runtime/start",
            post(post_telegram_runtime_start),
        )
        .route(
            "/api/v1/telegram/login/qr/start",
            post(post_telegram_qr_login_start),
        )
        .route(
            "/api/v1/telegram/login/qr/{setup_id}",
            get(get_telegram_qr_login_status).delete(delete_telegram_qr_login),
        )
        .route(
            "/api/v1/telegram/login/qr/{setup_id}/password",
            post(post_telegram_qr_login_password),
        )
        .route("/api/v1/telegram/chats", get(get_telegram_chats))
        .route(
            "/api/v1/telegram/sync/chats",
            post(post_telegram_sync_chats),
        )
        .route(
            "/api/v1/telegram/sync/history",
            post(post_telegram_sync_history),
        )
        .route(
            "/api/v1/telegram/messages",
            get(get_telegram_messages).post(post_telegram_fixture_message),
        )
        .route(
            "/api/v1/telegram/messages/send",
            post(post_telegram_manual_send),
        )
        .route(
            "/api/v1/telegram/media/download",
            post(post_telegram_media_download),
        )
        .route(
            "/api/v1/policies/templates",
            get(get_policy_templates).post(post_policy_template),
        )
        .route("/api/v1/policies", get(get_policies).post(post_policy))
        .route(
            "/api/v1/policies/telegram-send/dry-run",
            post(post_telegram_send_dry_run),
        )
        .route("/api/v1/calls", get(get_calls).post(post_call))
        .route(
            "/api/v1/calls/{call_id}/transcript",
            get(get_call_transcript).post(post_call_transcript_fixture),
        )
        .route(
            "/api/v1/whatsapp/accounts/fixture",
            post(post_whatsapp_fixture_account),
        )
        .route("/api/v1/whatsapp/sessions", get(get_whatsapp_sessions))
        .route(
            "/api/v1/whatsapp/messages",
            get(get_whatsapp_messages).post(post_whatsapp_fixture_message),
        )
}
