use super::support::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/api/v1/organizations",
            get(get_organizations).post(post_organization),
        )
        .route("/api/v1/organizations/search", get(get_organization_search))
        .route(
            "/api/v1/organizations/{org_id}",
            get(get_organization).put(put_organization),
        )
        .route(
            "/api/v1/organizations/{org_id}/archive",
            post(post_organization_archive),
        )
        .route(
            "/api/v1/organizations/{org_id}/identities",
            get(get_org_identities).post(post_org_identity),
        )
        .route(
            "/api/v1/organizations/{org_id}/aliases",
            get(get_org_aliases).post(post_org_alias),
        )
        .route(
            "/api/v1/organizations/{org_id}/domains",
            get(get_org_domains),
        )
        .route(
            "/api/v1/organizations/{org_id}/departments",
            get(get_org_departments).post(post_org_department),
        )
        .route(
            "/api/v1/organizations/{org_id}/persona-links",
            get(get_org_persona_links).post(post_org_persona_link),
        )
        .route(
            "/api/v1/organizations/{org_id}/person-links",
            get(get_org_persona_links).post(post_org_persona_link),
        )
        .route(
            "/api/v1/organizations/{org_id}/related",
            get(get_org_related),
        )
        .route(
            "/api/v1/organizations/{org_id}/timeline",
            get(get_org_timeline),
        )
        .route(
            "/api/v1/organizations/{org_id}/portals",
            get(get_org_portals),
        )
        .route(
            "/api/v1/organizations/{org_id}/procedures",
            get(get_org_procedures),
        )
        .route(
            "/api/v1/organizations/{org_id}/playbooks",
            get(get_org_playbooks),
        )
        .route(
            "/api/v1/organizations/{org_id}/templates",
            get(get_org_templates),
        )
        .route(
            "/api/v1/organizations/{org_id}/financial",
            get(get_org_financial),
        )
        .route(
            "/api/v1/organizations/{org_id}/contracts",
            get(get_org_contracts),
        )
        .route(
            "/api/v1/organizations/{org_id}/compliance",
            get(get_org_compliance),
        )
        .route(
            "/api/v1/organizations/{org_id}/services",
            get(get_org_services),
        )
        .route(
            "/api/v1/organizations/{org_id}/products",
            get(get_org_products),
        )
        .route(
            "/api/v1/organizations/{org_id}/enrichment",
            get(get_org_enrichment),
        )
        .route(
            "/api/v1/organizations/{org_id}/enrichment/{rid}/apply",
            post(post_org_enrich_apply),
        )
        .route("/api/v1/organizations/{org_id}/risks", get(get_org_risks))
        .route("/api/v1/organizations/{org_id}/health", get(get_org_health))
        .route(
            "/api/v1/organizations/{org_id}/watchlist",
            post(post_org_watchlist_toggle),
        )
        .route(
            "/api/v1/organizations/{org_id}/dossier",
            get(get_org_dossier),
        )
        .route("/api/v1/organizations/{org_id}/brief", get(get_org_brief))
        .route(
            "/api/v1/organizations/{org_id}/context-pack",
            get(get_org_context_pack),
        )
}
