use super::support::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        // ── ADR-0084: /api/v1/personas natively-named routes ──────────────
        .route("/api/v1/personas", get(get_personas))
        .route(
            "/api/v1/personas/owner",
            get(get_owner_persona).put(put_owner_persona),
        )
        .route("/api/v1/personas/search", get(get_persona_search))
        .route("/api/v1/personas/health", get(get_personas_health))
        .route("/api/v1/personas/watchlist", get(get_personas_watchlist))
        .route(
            "/api/v1/personas/search/expertise",
            get(get_persona_expertise_search),
        )
        .route(
            "/api/v1/personas/{persona_id}",
            get(get_persona).put(put_persona),
        )
        .route(
            "/api/v1/personas/{persona_id}/fingerprint",
            post(post_persona_fingerprint),
        )
        .route(
            "/api/v1/personas/{persona_id}/favorite",
            post(post_persona_favorite),
        )
        .route(
            "/api/v1/personas/{persona_id}/notes",
            put(put_persona_notes),
        )
        .route(
            "/api/v1/personas/{persona_id}/address-book",
            put(put_persona_address_book_membership),
        )
        .route(
            "/api/v1/personas/{persona_id}/identity",
            get(get_persona_identity),
        )
        .route(
            "/api/v1/personas/{persona_id}/identities",
            get(get_persona_identities).post(post_persona_identity),
        )
        .route(
            "/api/v1/personas/{persona_id}/identities/{identity_id}",
            delete(delete_persona_identity),
        )
        .route(
            "/api/v1/personas/{persona_id}/roles",
            get(get_persona_roles).post(post_persona_role),
        )
        .route(
            "/api/v1/personas/{persona_id}/roles/{role}",
            delete(delete_persona_role),
        )
        .route(
            "/api/v1/personas/{persona_id}/interaction-contexts",
            get(get_persona_interaction_contexts).post(post_persona_interaction_context),
        )
        .route(
            "/api/v1/personas/{persona_id}/interaction-contexts/{context_id}",
            delete(delete_persona_interaction_context),
        )
        .route(
            "/api/v1/personas/{persona_id}/facts",
            get(get_persona_facts).post(post_persona_fact),
        )
        .route(
            "/api/v1/personas/{persona_id}/memory-cards",
            get(get_persona_memory_cards).post(post_persona_memory_card),
        )
        .route(
            "/api/v1/personas/{persona_id}/preferences",
            get(get_persona_preferences).post(post_persona_preference),
        )
        .route(
            "/api/v1/personas/{persona_id}/timeline",
            get(get_persona_timeline).post(post_relationship_event),
        )
        .route(
            "/api/v1/personas/{persona_id}/snapshots",
            get(get_persona_snapshots),
        )
        .route(
            "/api/v1/personas/{persona_id}/history-diff",
            get(get_persona_history_diff),
        )
        .route(
            "/api/v1/personas/{persona_id}/enrichment",
            get(get_persona_enrichment),
        )
        .route(
            "/api/v1/personas/{persona_id}/enrichment/{result_id}/apply",
            post(post_persona_enrichment_apply),
        )
        .route(
            "/api/v1/personas/{persona_id}/enrichment/{result_id}/reject",
            post(post_persona_enrichment_reject),
        )
        .route(
            "/api/v1/personas/{persona_id}/expertise",
            get(get_persona_expertise),
        )
        .route(
            "/api/v1/personas/{persona_id}/promises",
            get(get_persona_promises),
        )
        .route(
            "/api/v1/personas/{persona_id}/risks",
            get(get_persona_risks),
        )
        .route(
            "/api/v1/personas/{persona_id}/investigate",
            post(post_persona_investigate),
        )
        .route(
            "/api/v1/personas/{persona_id}/dossier",
            get(get_persona_dossier),
        )
        .route(
            "/api/v1/personas/{persona_id}/dossier/review",
            put(put_persona_dossier_review),
        )
        .route(
            "/api/v1/personas/{persona_id}/meeting-prep",
            get(get_persona_meeting_prep),
        )
        .route(
            "/api/v1/personas/{persona_id}/analytics",
            get(get_persona_analytics),
        )
        .route(
            "/api/v1/personas/{persona_id}/export",
            get(get_persona_export_handler),
        )
        .route(
            "/api/v1/personas/{persona_id}/health",
            get(get_persona_health),
        )
        .route(
            "/api/v1/personas/{persona_id}/watchlist",
            post(post_persona_watchlist_toggle),
        )
        .route("/api/v1/identity-candidates", get(get_identity_candidates))
        .route(
            "/api/v1/identity-traces",
            get(get_identity_traces).post(post_identity_trace),
        )
        .route(
            "/api/v1/identity-traces/{identity_id}/assignment",
            put(put_identity_trace_assignment),
        )
        .route(
            "/api/v1/identity-candidates/{identity_candidate_id}/review",
            put(put_identity_candidate_review),
        )
}
