import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'

describe('AISettingsControlCenter boundary', () => {
  it('renders AI Hub from SettingsPage through explicit AI contracts', () => {
    const page = readFileSync(
      new URL('../views/SettingsPage.vue', import.meta.url),
      'utf8'
    )
    const panel = readFileSync(new URL('./AISettingsPanel.vue', import.meta.url), 'utf8')
    const modelCatalog = readFileSync(new URL('./AIModelCatalogPanel.vue', import.meta.url), 'utf8')
    const modelPicker = readFileSync(new URL('./AIModelPickerDialog.vue', import.meta.url), 'utf8')
    const wizard = readFileSync(new URL('./AIProviderConnectionWizard.vue', import.meta.url), 'utf8')
    const surface = readFileSync(
      new URL('../queries/useAISettingsSurface.ts', import.meta.url),
      'utf8'
    )
    const predicates = readFileSync(
      new URL('../queries/aiSettingsPredicates.ts', import.meta.url),
      'utf8'
    )
    const catalog = readFileSync(
      new URL('../queries/aiSettingsCatalog.ts', import.meta.url),
      'utf8'
    )
    const pagePresentation = readFileSync(
      new URL('../queries/settingsPagePresentation.ts', import.meta.url),
      'utf8'
    )
    const presentation = readFileSync(
      new URL('../queries/aiSettingsPresentation.ts', import.meta.url),
      'utf8'
    )
    const callback = readFileSync(
      new URL('../queries/aiProviderCallback.ts', import.meta.url),
      'utf8'
    )
    const panelPresentation = readFileSync(
      new URL('./aiSettingsPanelPresentation.ts', import.meta.url),
      'utf8'
    )
    const api = readFileSync(
      new URL('../api/aiControlCenter.ts', import.meta.url),
      'utf8'
    )

    expect(existsSync(new URL('./AISettingsControlCenter.vue', import.meta.url))).toBe(false)
    expect(page).not.toContain('import AISettingsControlCenter')
    expect(page).not.toContain('<AISettingsControlCenter')
    expect(page).toContain('import AISettingsPanel')
    expect(page).toContain('<AISettingsPanel')
    expect(page).toContain("selectedSection === 'ai'")
    expect(pagePresentation).toContain("label: 'Hub'")
    expect(pagePresentation).toContain("label: 'AI Hub'")
    expect(panel).toContain('settings-ai-tabs')
    expect(panel).not.toContain('settings-ai-tabs--side')
    expect(panel).not.toContain('settings-ai-workbench')
    expect(panel).toContain('Provider inventory')
    expect(panel).toContain('AI providers, local model downloads, model catalog and route selection.')
    expect(panel).toContain('Model routing')
    expect(panel).toContain('settings-ai-panel-providers')
    expect(panel).toContain('settings-ai-panel-models')
    expect(panel).toContain('settings-ai-panel-routes')
    expect(panel).toContain('settings-ai-provider-workbench')
    expect(panel).toContain('settings-ai-provider-sidebar')
    expect(panel).toContain('settings-ai-provider-detail-pane')
    expect(panel).toContain('providerListGroups')
    expect(panelPresentation).toContain('Local runtimes')
    expect(panelPresentation).toContain('CLI providers')
    expect(panelPresentation).toContain('Remote APIs')
    expect(panel).toContain('Provider detail')
    expect(panel).toContain('Capability access')
    expect(panel).toContain('Choose models')
    expect(panel).toContain('isModelPickerOpen')
    expect(panel).toContain('AIModelPickerDialog')
    expect(panel).not.toContain('settings-ai-compact-model-list')
    expect(panel).not.toContain('Open catalog')
    expect(panel).not.toContain('settings-ai-connect-summary')
    expect(panel).not.toContain('settings-ai-panel--local')
    expect(panel).not.toContain('settings-ai-panel--selected')
    expect(panel).toContain('AIModelCatalogPanel')
    expect(modelCatalog).toContain('providerModelGroups')
    expect(modelCatalog).toContain('settings-ai-model-provider-tabs')
    expect(modelCatalog).toContain('settings-ai-model-provider-tab')
    expect(modelCatalog).toContain('SearchInput')
    expect(modelCatalog).toContain('modelCatalogSearch')
    expect(modelCatalog).toContain('useAIModelCatalogController')
    expect(modelCatalog).toContain('settings-ai-model-availability-filter')
    expect(modelCatalog).toContain('Show only available models')
    expect(modelCatalog).toContain('Download queued')
    expect(modelCatalog).toContain('Not downloaded')
    expect(modelCatalog).toContain('settings-ai-model-progress-bar')
    expect(modelCatalog).toContain('class="icon-button"')
    expect(modelCatalog).toContain(':aria-label="t(\'Sync models\')"')
    expect(modelCatalog).toContain('selectedModelGroupModels')
    expect(modelCatalog).toContain('settings-ai-model-checkbox')
    expect(modelCatalog).toContain('modelCapabilityBadges')
    expect(modelCatalog).toContain('modelRuntimeFacts')
    expect(modelPicker).toContain('Choose models for Hermes')
    expect(modelPicker).toContain('settings-ai-model-picker-dialog')
    expect(modelPicker).toContain('settings-ai-model-picker__list')
    expect(modelPicker).toContain('surface.selectedProviderModels.value')
    expect(modelPicker).toContain('Download queued')
    expect(modelPicker).toContain('Not downloaded')
    expect(modelPicker).toContain('handleCloseDialog')
    expect(modelPicker).toContain('handleUpdateOpen')
    expect(modelPicker).not.toContain('closeDialog')
    expect(modelPicker).not.toContain('updateOpen')
    expect(panel).not.toContain('function modelCapabilities(')
    expect(panel).not.toContain('modelCapabilities(model)')
    expect(panel).toContain('settings-ai-route-board')
    expect(panel).toContain('settings-ai-route-board__header-actions')
    expect(panel).toContain('settings-ai-route-row__meta')
    expect(panel).toContain('handleRefreshModelRoutes')
    expect(panel).toContain('AIProviderConnectionWizard')
    expect(panel).toContain('handleOpenProviderWizard')
    expect(panel).toContain('handleSetActiveTab')
    expect(panel).toContain('handleOpenModelPicker')
    expect(panel).toContain('handleSetModelPickerOpen')
    expect(panel).toContain('handleSelectProviderListItem')
    expect(panel).toContain('handleRefreshLocalAuth')
    expect(panel).toContain('handleOpenLocalAuthCallback')
    expect(panel).toContain('handleToggleSelectedProvider')
    expect(panel).toContain('handleUpdateSelectedProviderConsent')
    expect(panel).toContain('handleTestSelectedProvider')
    expect(panel).toContain('handleSyncSelectedProviderModels')
    expect(wizard).toContain('Steps')
    expect(wizard).toContain('SearchableSelect')
    expect(wizard).toContain('Подключение AI провайдера')
    expect(wizard).toContain('Шаги мастера')
    expect(wizard).toContain('Синхронизировать модели')
    expect(wizard).toContain('v-model:step="currentStep"')
    expect(wizard).toContain('type="password"')
    expect(wizard).toContain('useAIProviderConnectionWizardController')
    expect(wizard).toContain('handleUpdateApiProviderDisplayName')
    expect(wizard).toContain('handleUpdateApiProviderKey')
    expect(wizard).toContain('handleUpdateApiBaseUrl')
    expect(wizard).toContain('handleUpdateApiToken')
    expect(wizard).toContain('handleUpdateApiConsent')
    expect(wizard).toContain('handleSetCurrentStep')
    expect(wizard).not.toContain('updateText(surface.api')
    expect(wizard).not.toContain('updateBoolean(surface.api')
    expect(panel).toContain('useAISettingsPanelController')
    expect(modelPicker).toContain('useAIModelPickerController')
    expect(panel).toContain('surface.selectedProviderId')
    expect(panel).toContain('Open callback')
    expect(surface).toContain('useAiSettingsOverviewQuery')
    expect(surface).toContain('useCreateAiProviderMutation')
    expect(surface).toContain('useUpdateAiModelAvailabilityMutation')
    expect(surface).toContain('useUpdateAiModelRouteMutation')
    expect(surface).toContain('handleRefreshModelRoutes')
    expect(surface).toContain('await overviewQuery.refetch()')
    expect(surface).toContain('useStartAiProviderAuthMutation')
    expect(callback).toContain('hermes:ai-provider-connected')
    expect(surface).toContain('DEFAULT_API_PROVIDER_PRESETS')
    expect(predicates).toContain('modelUsableForSlot')
    expect(predicates).toContain('providerIsBuiltInOllama')
    expect(presentation).toContain('SLOT_DESCRIPTIONS')
    expect(presentation).toContain('buildAiModelRouteRows')
    expect(catalog).toContain('Extraction and categorization')
    expect(catalog).toContain('Raw OpenAI-compatible API')
    expect(catalog).toContain('openrouter')
    expect(catalog).toContain('groq')
    expect(surface).not.toContain('selectedApiPresetKeys')
    expect(surface).not.toContain('handlePresetSelection')
    expect(api).toContain('/api/v1/ai/providers')
    expect(api).toContain('/api/v1/ai/models/availability')
    expect(api).toContain('/api/v1/ai/model-downloads')
    expect(api).toContain('/api/v1/ai/provider-auth/start')
    expect(api).toContain('/api/v1/ai/model-routes/')
  })
})
