import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'

describe('AISettingsControlCenter boundary', () => {
  it('renders AI Control Center from SettingsPage through explicit AI contracts', () => {
    const page = readFileSync(
      new URL('../views/SettingsPage.vue', import.meta.url),
      'utf8'
    )
    const panel = readFileSync(new URL('./AISettingsPanel.vue', import.meta.url), 'utf8')
    const modelCatalog = readFileSync(new URL('./AIModelCatalogPanel.vue', import.meta.url), 'utf8')
    const wizard = readFileSync(new URL('./AIProviderConnectionWizard.vue', import.meta.url), 'utf8')
    const surface = readFileSync(
      new URL('../queries/useAISettingsSurface.ts', import.meta.url),
      'utf8'
    )
    const api = readFileSync(
      new URL('../api/aiControlCenter.ts', import.meta.url),
      'utf8'
    )

    expect(existsSync(new URL('./AISettingsControlCenter.vue', import.meta.url))).toBe(false)
    expect(page).not.toContain('import AISettingsControlCenter')
    expect(page).not.toContain('<AISettingsControlCenter')
    expect(page).toContain('import AISettingsPanel')
    expect(page).toContain('<AISettingsPanel')
    expect(page).toContain("store.selectedSection === 'ai'")
    expect(panel).toContain('settings-ai-tabs')
    expect(panel).not.toContain('settings-ai-tabs--side')
    expect(panel).not.toContain('settings-ai-workbench')
    expect(panel).toContain('Provider setup')
    expect(panel).toContain('Model catalog')
    expect(panel).toContain('Action routing')
    expect(panel).toContain('settings-ai-panel-providers')
    expect(panel).toContain('settings-ai-panel-models')
    expect(panel).toContain('settings-ai-panel-routes')
    expect(panel).toContain('settings-ai-provider-workbench')
    expect(panel).toContain('settings-ai-provider-sidebar')
    expect(panel).toContain('settings-ai-provider-detail-pane')
    expect(panel).toContain('providerListGroups')
    expect(panel).toContain('Local runtimes')
    expect(panel).toContain('CLI providers')
    expect(panel).toContain('Remote APIs')
    expect(panel).toContain('Provider detail')
    expect(panel).toContain('Capability access')
    expect(panel).toContain('Choose models')
    expect(panel).toContain('isModelPickerOpen')
    expect(panel).toContain('Choose models for Hermes')
    expect(panel).toContain('settings-ai-model-picker-dialog')
    expect(panel).toContain('settings-ai-model-picker__list')
    expect(panel).toContain('surface.selectedProviderModels.value')
    expect(panel).not.toContain('settings-ai-compact-model-list')
    expect(panel).not.toContain('Open catalog')
    expect(panel).not.toContain('settings-ai-connect-summary')
    expect(panel).not.toContain('settings-ai-panel--local')
    expect(panel).not.toContain('settings-ai-panel--selected')
    expect(panel).toContain('AIModelCatalogPanel')
    expect(modelCatalog).toContain('providerModelGroups')
    expect(modelCatalog).toContain('settings-ai-model-provider-tabs')
    expect(modelCatalog).toContain('settings-ai-model-provider-tab')
    expect(modelCatalog).toContain('SearchInput')
    expect(modelCatalog).toContain('modelCatalogSearch')
    expect(modelCatalog).toContain('showAvailableModelsOnly = ref(true)')
    expect(modelCatalog).toContain('settings-ai-model-availability-filter')
    expect(modelCatalog).toContain('Show only available models')
    expect(modelCatalog).toContain('class="icon-button"')
    expect(modelCatalog).toContain(':aria-label="t(\'Sync models\')"')
    expect(modelCatalog).toContain('selectedModelGroupModels')
    expect(modelCatalog).toContain('settings-ai-model-checkbox')
    expect(modelCatalog).toContain('modelCapabilityBadges')
    expect(modelCatalog).toContain('modelRuntimeFacts')
    expect(panel).not.toContain('function modelCapabilities(')
    expect(panel).not.toContain('modelCapabilities(model)')
    expect(panel).toContain('settings-ai-route-board')
    expect(panel).toContain('settings-ai-route-board__header-actions')
    expect(panel).toContain('settings-ai-route-row__meta')
    expect(panel).toContain('refreshModelRoutes')
    expect(panel).toContain('AIProviderConnectionWizard')
    expect(panel).toContain('isProviderWizardOpen = true')
    expect(wizard).toContain('Steps')
    expect(wizard).toContain('SearchableSelect')
    expect(wizard).toContain('Параметры API')
    expect(wizard).toContain('Проверка')
    expect(wizard).toContain('Модели Hermes')
    expect(wizard).toContain('v-model:step="currentStep"')
    expect(wizard).toContain('type="password"')
    expect(wizard).toContain('surface.handleCreateApiProvider')
    expect(wizard).toContain('surface.handleTestProvider')
    expect(wizard).toContain('surface.handleSyncModels')
    expect(wizard).toContain('surface.handleModelAvailability')
    expect(wizard).toContain('surface.handlePresetSelect')
    expect(panel).toContain('surface.handleRouteSelection')
    expect(panel).toContain('surface.handleConnectLocalPreset')
    expect(panel).toContain('Open callback')
    expect(surface).toContain('useAiSettingsOverviewQuery')
    expect(surface).toContain('useCreateAiProviderMutation')
    expect(surface).toContain('useUpdateAiModelAvailabilityMutation')
    expect(surface).toContain('useUpdateAiModelRouteMutation')
    expect(surface).toContain('handleRefreshModelRoutes')
    expect(surface).toContain('await overviewQuery.refetch()')
    expect(surface).toContain('useStartAiProviderAuthMutation')
    expect(surface).toContain('hermes:ai-provider-connected')
    expect(surface).toContain('Extraction and categorization')
    expect(surface).toContain('Raw OpenAI-compatible API')
    expect(surface).toContain('openrouter')
    expect(surface).toContain('groq')
    expect(surface).not.toContain('selectedApiPresetKeys')
    expect(surface).not.toContain('handlePresetSelection')
    expect(api).toContain('/api/v1/ai/providers')
    expect(api).toContain('/api/v1/ai/models/availability')
    expect(api).toContain('/api/v1/ai/provider-auth/start')
    expect(api).toContain('/api/v1/ai/model-routes/')
  })
})
