import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'

describe('TraceLogsSettings boundary', () => {
  it('rebuilds trace graph UI inside Settings while keeping platform event tracing ownership', () => {
    const page = readFileSync(new URL('../views/SettingsPage.vue', import.meta.url), 'utf8')
    const settingsStore = readFileSync(new URL('../stores/settings.ts', import.meta.url), 'utf8')
    const pageSurface = readFileSync(new URL('../queries/useSettingsPageSurface.ts', import.meta.url), 'utf8')
    const settingsSurface = readFileSync(new URL('../queries/useTraceLogsSettingsSurface.ts', import.meta.url), 'utf8')
    const panel = readFileSync(new URL('./TraceLogsSettingsPanel.vue', import.meta.url), 'utf8')
    const presentation = readFileSync(new URL('./eventTraceSettingsPresentation.ts', import.meta.url), 'utf8')
    const platformApi = readFileSync(new URL('../../../platform/event-tracing/api.ts', import.meta.url), 'utf8')
    const platformQueries = readFileSync(new URL('../../../platform/event-tracing/queries.ts', import.meta.url), 'utf8')
    const main = readFileSync(new URL('../../../main.ts', import.meta.url), 'utf8')

    expect(existsSync(new URL('./TraceLogsSettingsPanel.vue', import.meta.url))).toBe(true)
    expect(settingsStore).toContain("'logs-traces'")
    expect(pageSurface).toContain("id: 'logs-traces'")
    expect(pageSurface).toContain("label: 'Logs & Traces'")
    expect(pageSurface).toContain('useTraceLogsSettingsSurface')
    expect(page).toContain('import TraceLogsSettingsPanel')
    expect(page).toContain("store.selectedSection === 'logs-traces'")
    expect(page).toContain(':surface="traceLogsSettings"')
    expect(main).toContain("import './styles/settings-trace-logs.css'")

    expect(settingsSurface).toContain('useEventsQuery')
    expect(settingsSurface).toContain('useEventTraceByEventIdQuery')
    expect(settingsSurface).toContain('useEventTraceByCorrelationIdQuery')
    expect(settingsSurface).toContain('activeTraceDataTab')
    expect(settingsSurface).toContain('recentEventsPageStarts')
    expect(settingsSurface).toContain('useEventsQuery(recentEventsAfterPosition')
    expect(settingsSurface).toContain('pagedTraceEventRows')
    expect(settingsSurface).toContain('pagedRecentEventRows')
    expect(settingsSurface).not.toContain('ApiClient')
    expect(settingsSurface).not.toMatch(/\bfetch\s*\(/)

    expect(panel).toContain('settings-trace-graph-svg')
    expect(panel).toContain('settings-trace-node')
    expect(panel).toContain('settings-trace-edge')
    expect(panel).toContain('settings-trace-data-tabs')
    expect(panel).toContain('settings-trace-data-search')
    expect(panel).toContain('surface.pagedTraceEventRows.value.rows')
    expect(panel).toContain('surface.pagedRecentEventRows.value.rows')
    expect(panel).toContain('surface.handleTraceEventsNextPage')
    expect(panel).toContain('surface.handleRecentEventsNextPage')
    expect(panel).toContain('surface.handleSelectTraceNode')
    expect(panel).toContain('surface.handleUseRecentEvent')

    expect(presentation).toContain('buildTraceGraph')
    expect(presentation).toContain('causation')
    expect(presentation).toContain('filterTraceEventRows')
    expect(presentation).toContain('paginateTraceRows')
    expect(platformApi).toContain('/api/v1/events?')
    expect(platformApi).toContain('/api/v1/events/')
    expect(platformApi).toContain('/api/v1/event-traces/')
    expect(platformQueries).toContain('useEventsQuery')
    expect(platformQueries).toContain('eventTraceQueryKeys.events')
  })
})
