import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

describe('CommunicationFolderStrip folder management boundary', () => {
	it('uses Zod/Vee folder forms and TanStack folder mutations', () => {
		const source = readFileSync(
			new URL('./CommunicationFolderStrip.vue', import.meta.url),
			'utf8'
		)

		expect(source).toContain("from 'vee-validate'")
		expect(source).toContain("from '@tanstack/vue-virtual'")
		expect(source).toContain('../forms/mailFolderForm')
		expect(source).toContain('useCommunicationFoldersQuery')
		expect(source).toContain('useVirtualizer')
		expect(source).toContain('horizontal: true')
		expect(source).toContain('virtualFolders')
		expect(source).toContain('folderVirtualTotalSize')
		expect(source).toContain('v-for="virtualFolder in virtualFolders"')
		expect(source).toContain('folderRows[virtualFolder.index]')
		expect(source).toContain('hasNextPage')
		expect(source).toContain('isFetchingNextPage')
		expect(source).toContain('fetchNextPage')
		expect(source).toContain('handleFolderVirtualScroll')
		expect(source).toContain('@scroll="handleFolderVirtualScroll"')
		expect(source).toContain('useCopyMessageToFolderMutation')
		expect(source).toContain('useCreateCommunicationFolderMutation')
		expect(source).toContain('useUpdateCommunicationFolderMutation')
		expect(source).toContain('useDeleteCommunicationFolderMutation')
		expect(source).toContain('useMoveMessageToFolderMutation')
		expect(source).toContain('useCommunicationFolderReorder')
		expect(source).toContain('orderCommunicationFolderDisplayRows')
		expect(source).toContain('createChildFolderDraft')
		expect(source).toContain('mailFolderHierarchyDeleteImpact')
		expect(source).toContain('mailFolderParentPathOptions')
		expect(source).toContain('splitCommunicationFolderName')
		expect(source).toContain('validateCommunicationFolderParentPath')
		expect(source).toContain('const orderedFolders = computed(() => folderRows.value.map((row) => row.folder))')
		expect(source).toContain('const parentPathOptions = computed(() => mailFolderParentPathOptions(orderedFolders.value, editingFolder.value))')
		expect(source).toContain('const folderPathPreview = computed(() => composeCommunicationFolderName(parentPath.value, leafName.value))')
		expect(source).toContain('function openCreateChildDialog(folder: CommunicationFolder)')
		expect(source).toContain(':description="folderDialogDescription"')
		expect(source).toContain(':description="deleteDialogDescription"')
		expect(source).toContain('list="mail-folder-parent-path-options"')
		expect(source).toContain('<span>Folder name</span>')
		expect(source).toContain('class="mail-folder-path-preview"')
		expect(source).toContain('Add child folder under')
		expect(source).toContain('class="mail-folder-delete-impact"')
		expect(source).toContain('activeId: string')
		expect(source).toContain('select: [folderId: string]')
		expect(source).toContain("emit('select', folderRows[virtualFolder.index].folder.folder_id)")
		expect(source).toContain('@dragover="handleFolderDragOver"')
		expect(source).toContain('@drop.prevent="handleFolderDrop($event, folderRows[virtualFolder.index].folder)"')
		expect(source).toContain('@dragstart="folderReorder.handleDragStart($event, folderRows[virtualFolder.index].folder)"')
		expect(source).toContain('@dragend="folderReorder.handleDragEnd"')
		expect(source).toContain('folderReorder.canHandleDragOver(event)')
		expect(source).toContain('folderIndent(folderRows[virtualFolder.index])')
		expect(source).toContain('@drop.prevent="handleFolderDrop($event, folderRows[virtualFolder.index].folder)"')
		expect(source).toContain('@dragstart="folderReorder.handleDragStart($event, folderRows[virtualFolder.index].folder)"')
		expect(source).toContain('parseCommunicationMessageDragPayload')
		expect(source).toContain('folderReorder.handleDrop(event, folder)')
		expect(source).not.toContain('../api/communications')
		expect(source).not.toContain('ApiClient')
	})
})
