import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const componentPath = resolve(dirname(fileURLToPath(import.meta.url)), 'ComposeTemplatePicker.vue')

describe('ComposeTemplatePicker boundaries', () => {
	it('uses TanStack Query hooks for template list and render operations', () => {
		const source = readFileSync(componentPath, 'utf8')

		expect(source).not.toContain('../api/communications')
		expect(source).toContain('useRichTemplatesQuery')
		expect(source).toContain('useRenderRichTemplateMutation')
		expect(source).toContain('useCreateRichTemplateMutation')
		expect(source).toContain("emit('apply'")
		expect(source).toContain("emit('saved'")
		expect(source).toContain("emit('deleted'")
		expect(source).toContain('updateSelectedTemplate')
		expect(source).toContain('templateId: template.template_id')
		expect(source).toContain('useDeleteRichTemplateMutation')
		expect(source).toContain('usePreviewRichTemplateMailMergeMutation')
		expect(source).toContain('deleteSelectedTemplate')
		expect(source).toContain('missingTemplateVariables')
		expect(source).toContain('parseTemplateMailMergePreviewRows')
		expect(source).toContain('stringifyTemplateMailMergePreviewRows')
		expect(source).toContain('resolveTemplateVariableValues')
		expect(source).toContain('storedTemplateDiagnosticMessages')
		expect(source).toContain('orderedTemplates')
		expect(source).toContain('templateDiagnosticCount')
		expect(source).toContain('templateUpdatedLabel')
		expect(source).toContain('TemplateRecipientMappingPanel')
		expect(source).toContain('TemplateSaveForm')
		expect(source).toContain('templateLibraryCategoryOptions')
		expect(source).toContain('selectedCategory')
		expect(source).toContain('deriveTemplateLibraryCategories')
		expect(source).toContain('applyTemplateRecipientMapping')
		expect(source).toContain('buildTemplateRecipientPreviewRows')
		expect(source).toContain('recipientPreviewSummary')
		expect(source).toContain('suggestTemplateSaveName')
		expect(source).toContain("import './ComposeTemplatePicker.css'")
		expect(source).toContain('const isSameTemplate = Boolean(template && previousTemplate && template.template_id === previousTemplate.template_id)')
		expect(source).toContain('preserveExisting: isSameTemplate')
		expect(source).toContain('Mail merge preview')
		expect(source).toContain('@build-preview="buildPreviewRowsFromRecipients"')
		expect(source).toContain('previewMailMergeMutation')
		expect(source).toContain('previewRowsText')
		expect(source).toContain('previewResult')
		expect(source).toContain('mergeValidationMessage')
		expect(source).toContain('selectedTemplateValidationMessage')
		expect(source).toContain('template-diagnostics')
		expect(source).toContain('templateContentDiagnostics')
		expect(source).toContain('saveValidationMessage')
		expect(source).toContain("openSaveTemplate('duplicate')")
		expect(source).toContain('Save copy')
		expect(source).toContain('closeSaveTemplate')
		expect(source).toContain('result.rendered.unresolved_variables')
		expect(source).toContain('result.rendered.malformed_placeholders')
	})
})
