import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

describe('SavedSearchStrip prefetch boundary', () => {
  it('prefetches saved-search mail list results without direct API calls from the component', () => {
    const source = readFileSync(new URL('./SavedSearchStrip.vue', import.meta.url), 'utf8')

    expect(source).toContain("from '@tanstack/vue-virtual'")
    expect(source).toContain('useVirtualizer')
    expect(source).toContain('horizontal: true')
    expect(source).toContain('virtualSmartFolders')
    expect(source).toContain('virtualSavedSearches')
    expect(source).toContain('smartFolderVirtualTotalSize')
    expect(source).toContain('savedSearchVirtualTotalSize')
    expect(source).toContain('v-for="virtualItem in virtualSmartFolders"')
    expect(source).toContain('v-for="virtualItem in virtualSavedSearches"')
    expect(source).toContain('fetchNextPage: fetchNextSmartFolderPage')
    expect(source).toContain('fetchNextPage: fetchNextSavedSearchPage')
    expect(source).toContain('savedSearchFilterChips')
    expect(source).toContain('savedSearchPresetOptions')
    expect(source).toContain('savedSearchWorkflowOptions')
    expect(source).toContain('savedSearchLocalStateOptions')
    expect(source).toContain('savedSearchChannelOptions')
    expect(source).toContain('normalizeSavedSearchBuilderState')
    expect(source).toContain('composeSavedSearchRuleTreeQuery')
    expect(source).toContain('validateSavedSearchRuleTree')
    expect(source).toContain('SavedSearchRuleGroupEditor')
    expect(source).toContain('searchRuleTree')
    expect(source).toContain('normalizeQueryIntoBuilder(formValues.query)')
    expect(source).toContain('const effectiveQueryPreview = computed(() =>')
    expect(source).toContain('const ruleValidation = computed(() => validateSavedSearchRuleTree(searchRuleTree.value))')
    expect(source).toContain('Rules Builder')
    expect(source).toContain('Effective query')
    expect(source).toContain('saved-search-effective-query')
    expect(source).toContain('saved-search-rule-error')
    expect(source).toContain(':disabled="isSaving || !ruleValidation.isValid"')
    expect(source).toContain('currentQuery')
    expect(source).toContain('currentWorkflowState')
    expect(source).toContain('currentLocalState')
    expect(source).toContain('currentChannelKind')
    expect(source).toContain('currentSearchDefaults')
    expect(source).toContain('activeFilterChips')
    expect(source).toContain('applyPreset(preset)')
    expect(source).toContain('v-for="chip in activeFilterChips"')
    expect(source).toContain('handleSmartFolderVirtualScroll')
    expect(source).toContain('handleSavedSearchVirtualScroll')
    expect(source).toContain('@scroll="handleSmartFolderVirtualScroll"')
    expect(source).toContain('@scroll="handleSavedSearchVirtualScroll"')
    expect(source).toContain('useSavedSearchMailListPrefetch')
    expect(source).toContain('handleSavedSearchPrefetch')
    expect(source).toContain('@mouseenter="handleSavedSearchPrefetch(smartFolders[virtualItem.index])"')
    expect(source).toContain('@focus="handleSavedSearchPrefetch(savedSearches[virtualItem.index])"')
    expect(source).not.toContain('../api/')
    expect(source).not.toContain('ApiClient')
  })
})
