import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

describe('ThreadConversationView boundary', () => {
  it('renders thread messages as a conversation timeline without fetching directly', () => {
    const source = readFileSync(
      new URL('./ThreadConversationView.vue', import.meta.url),
      'utf8'
    )

    expect(source).toContain('thread: MailThreadSummary')
    expect(source).toContain('messages: ThreadMessage[]')
    expect(source).toContain('isSendingReply: boolean')
    expect(source).toContain('v-for="message in messages"')
    expect(source).toContain('expandedMessageIds')
    expect(source).toContain('activeReplyMessageId')
    expect(source).toContain('inlineReplyHtml')
    expect(source).toContain('activeReplyDraftId')
    expect(source).toContain('showQuotedContent')
    expect(source).toContain('autoExpandedThreadId')
    expect(source).toContain('expansionSummary')
    expect(source).toContain('expandedMessageCount')
    expect(source).toContain('hasQuotedMessages')
    expect(source).toContain('canExpandAllMessages')
    expect(source).toContain('canCollapseAllMessages')
    expect(source).toContain('startInlineReply')
    expect(source).toContain('cancelInlineReply')
    expect(source).toContain('continueReplyInCompose')
    expect(source).toContain('saveInlineReplyDraft')
    expect(source).toContain('sendInlineReply')
    expect(source).toContain('expandAllMessages')
    expect(source).toContain('collapseAllMessages')
    expect(source).toContain('ThreadInlineReplyComposer')
    expect(source).toContain('ThreadAttachmentInsightPanel')
    expect(source).toContain('useTranslateThreadMutation')
    expect(source).toContain('defaultExpandedThreadMessageIds')
    expect(source).toContain('hasQuotedThreadMessages')
    expect(source).toContain('summarizeThreadExpansion')
    expect(source).toContain('threadTranslationTarget')
    expect(source).toContain('threadTranslationResult')
    expect(source).toContain('threadTranslationError')
    expect(source).toContain('translatedThreadCount')
    expect(source).toContain('translatedTextForMessage')
    expect(source).toContain('handleTranslateThread')
    expect(source).toContain('props.thread.thread_id')
    expect(source).toContain('expandedMessageIds.value = new Set()')
    expect(source).toContain("autoExpandedThreadId.value = ''")
    expect(source).toContain('autoExpandedThreadId.value === props.thread.thread_id')
    expect(source).toContain('expandedMessageIds.value = defaultExpandedThreadMessageIds(messages)')
    expect(source).toContain("targetLanguage: threadTranslationTarget.value")
    expect(source).toContain('formatAttachmentSize')
    expect(source).toContain('scanStatusClass')
    expect(source).toContain('previewThreadMessageBody')
    expect(source).toContain('splitThreadMessageBody')
    expect(source).toContain('thread-translation-panel')
    expect(source).toContain('v-if="threadTranslationResult"')
    expect(source).toContain('translatedTextForMessage(message.message_id)')
    expect(source).toContain('Thread translation review')
    expect(source).toContain('Expand all')
    expect(source).toContain('Collapse all')
    expect(source).toContain("{{ showQuotedContent ? 'Hide quoted' : 'Show quoted' }}")
    expect(source).toContain('message-quoted')
    expect(source).toContain('showQuotedContent && quotedBody(message)')
    expect(source).toContain('message.attachments.length > 0')
    expect(source).toContain('message-attachment')
    expect(source).toContain('Thread message attachments')
    expect(source).toContain('<ThreadAttachmentInsightPanel :attachment="attachment" />')
    expect(source).toContain('v-model:body-html="inlineReplyHtml"')
    expect(source).toContain('@save-draft="saveInlineReplyDraft(message)"')
    expect(source).toContain('@continue-in-compose="continueReplyInCompose(message)"')
    expect(source).toContain('@send="sendInlineReply(message)"')
    expect(source).toContain('toggleMessageExpanded')
    expect(source).toContain('isMessageExpanded')
    expect(source).toContain('openMessage: [messageId: string]')
    expect(source).toContain('replyToMessage: [message: ThreadMessage, bodyHtml: string, draftId: string]')
    expect(source).toContain('saveReplyDraft: [message: ThreadMessage, bodyHtml: string, draftId: string]')
    expect(source).toContain('sendReply: [message: ThreadMessage, bodyHtml: string, draftId: string]')
    expect(source).toContain("emit('replyToMessage', message, inlineReplyHtml.value, activeReplyDraftId.value)")
    expect(source).toContain("emit('saveReplyDraft', message, inlineReplyHtml.value, activeReplyDraftId.value)")
    expect(source).toContain("emit('sendReply', message, inlineReplyHtml.value, activeReplyDraftId.value)")
    expect(source).toContain('message.body_text')
    expect(source).not.toContain('reviewingReplyMessageId')
    expect(source).not.toContain('RichComposeEditor')
    expect(source).not.toContain('fetch(')
    expect(source).not.toContain('ApiClient')
  })
})
