export const telegramQueryKeys = {
  capabilities: ['telegram', 'capabilities'] as const,
  accountCapabilities: ['telegram', 'account-capabilities'] as const,
  accounts: ['telegram', 'accounts'] as const,
  chats: ['telegram', 'chats'] as const,
  folders: ['telegram', 'folders'] as const,
  chatDetail: ['telegram', 'chat-detail'] as const,
  chatMembers: ['telegram', 'chat-members'] as const,
  messages: ['telegram', 'messages'] as const,
  runtime: ['telegram', 'runtime'] as const,
  calls: ['telegram', 'calls'] as const,
  callTranscript: ['telegram', 'call-transcript'] as const,
  topics: ['telegram', 'topics'] as const,
  topicMessages: ['telegram', 'topic-messages'] as const,
  topicSearch: ['telegram', 'topic-search'] as const,
}
