//! WhatsApp WebView companion routes composed without router-wide handler facades.

use axum::Router;
use axum::routing::{get, post};

use crate::app::provider_runtime_handlers::whatsapp;
use crate::app::state::AppState;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/api/v1/integrations/whatsapp/capabilities",
            get(whatsapp::accounts::get_whatsapp_capabilities),
        )
        .route(
            "/api/v1/integrations/whatsapp/accounts/{account_id}/capabilities",
            get(whatsapp::accounts::get_whatsapp_account_capabilities),
        )
        .route(
            "/api/v1/integrations/whatsapp/accounts",
            get(whatsapp::accounts::get_whatsapp_accounts).post(whatsapp::accounts::post_whatsapp_account),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/status",
            get(whatsapp::accounts::get_whatsapp_runtime_status),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/start",
            post(whatsapp::accounts::post_whatsapp_runtime_start),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/stop",
            post(whatsapp::accounts::post_whatsapp_runtime_stop),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/revoke",
            post(whatsapp::accounts::post_whatsapp_runtime_revoke),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/relink",
            post(whatsapp::accounts::post_whatsapp_runtime_relink),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/rotate",
            post(whatsapp::accounts::post_whatsapp_runtime_rotate),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/remove",
            post(whatsapp::accounts::post_whatsapp_runtime_remove),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime/health",
            get(whatsapp::accounts::get_whatsapp_runtime_health),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/messages",
            post(whatsapp::post_whatsapp_runtime_bridge_message),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/message-updates",
            post(whatsapp::post_whatsapp_runtime_bridge_message_update),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/message-deletes",
            post(whatsapp::post_whatsapp_runtime_bridge_message_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/receipts",
            post(whatsapp::post_whatsapp_runtime_bridge_receipt),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/dialogs",
            post(whatsapp::post_whatsapp_runtime_bridge_dialog),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/participants",
            post(whatsapp::post_whatsapp_runtime_bridge_participant),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/reactions",
            post(whatsapp::post_whatsapp_runtime_bridge_reaction),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/media",
            post(whatsapp::post_whatsapp_runtime_bridge_media),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/media-lifecycle",
            post(whatsapp::post_whatsapp_runtime_bridge_media_lifecycle),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/statuses",
            post(whatsapp::post_whatsapp_runtime_bridge_status),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/status-views",
            post(whatsapp::post_whatsapp_runtime_bridge_status_view),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/status-deletes",
            post(whatsapp::post_whatsapp_runtime_bridge_status_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/presence",
            post(whatsapp::post_whatsapp_runtime_bridge_presence),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/calls",
            post(whatsapp::post_whatsapp_runtime_bridge_call),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/runtime-events",
            post(whatsapp::post_whatsapp_runtime_bridge_runtime_event),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/sync-lifecycle",
            post(whatsapp::post_whatsapp_runtime_bridge_sync_lifecycle),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/commands/claim",
            post(whatsapp::post_whatsapp_runtime_bridge_claim_commands),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/commands/{command_id}/failed",
            post(whatsapp::post_whatsapp_runtime_bridge_command_failed),
        )
        .route(
            "/api/v1/integrations/whatsapp/runtime-bridge/sessions/authorized",
            post(whatsapp::post_whatsapp_runtime_bridge_authorized_session),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/chats",
            post(whatsapp::sync_chats::post_whatsapp_sync_chats),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/history",
            post(whatsapp::sync_history::post_whatsapp_sync_history),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/conversations/{provider_chat_id}/members",
            post(whatsapp::post_whatsapp_sync_members),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/statuses",
            post(whatsapp::sync_statuses::post_whatsapp_sync_statuses),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/presence",
            post(whatsapp::sync_presence::post_whatsapp_sync_presence),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/calls",
            post(whatsapp::sync_calls::post_whatsapp_sync_calls),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/contacts",
            post(whatsapp::post_whatsapp_sync_contacts),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-sync/media",
            post(whatsapp::post_whatsapp_sync_media),
        )
        .route(
            "/api/v1/integrations/whatsapp/login/qr/start",
            post(whatsapp::accounts::post_whatsapp_qr_link_start),
        )
        .route(
            "/api/v1/integrations/whatsapp/login/pair-code/start",
            post(whatsapp::accounts::post_whatsapp_pair_code_link_start),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/send",
            post(whatsapp::messages::post_whatsapp_command_send_text),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/reply",
            post(whatsapp::messages::post_whatsapp_command_reply),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/forward",
            post(whatsapp::messages::post_whatsapp_command_forward),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/edit",
            post(whatsapp::messages::post_whatsapp_command_edit),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/delete",
            post(whatsapp::messages::post_whatsapp_command_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/{message_id}/reactions",
            post(whatsapp::messages::post_whatsapp_command_react)
                .delete(whatsapp::messages::delete_whatsapp_command_react),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-media/upload",
            post(whatsapp::media::post_whatsapp_media_upload),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-media/download",
            post(whatsapp::media::post_whatsapp_media_download),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/messages/voice-note",
            post(whatsapp::media::post_whatsapp_voice_note_send),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/statuses/publish",
            post(whatsapp::statuses::post_whatsapp_status_publish),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/join",
            post(whatsapp::conversations::post_whatsapp_conversation_join_group),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/read",
            post(whatsapp::conversations::post_whatsapp_conversation_mark_read),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unread",
            post(whatsapp::conversations::post_whatsapp_conversation_mark_unread),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/archive",
            post(whatsapp::conversations::post_whatsapp_conversation_archive),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unarchive",
            post(whatsapp::conversations::post_whatsapp_conversation_unarchive),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/mute",
            post(whatsapp::conversations::post_whatsapp_conversation_mute),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unmute",
            post(whatsapp::conversations::post_whatsapp_conversation_unmute),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/pin",
            post(whatsapp::conversations::post_whatsapp_conversation_pin),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/unpin",
            post(whatsapp::conversations::post_whatsapp_conversation_unpin),
        )
        .route(
            "/api/v1/integrations/whatsapp/provider-commands/conversations/{conversation_id}/leave",
            post(whatsapp::conversations::post_whatsapp_conversation_leave_group),
        )
        .route(
            "/api/v1/integrations/whatsapp/commands",
            get(whatsapp::get_whatsapp_commands),
        )
        .route(
            "/api/v1/integrations/whatsapp/commands/{command_id}/retry",
            post(whatsapp::post_whatsapp_command_retry),
        )
        .route(
            "/api/v1/integrations/whatsapp/commands/{command_id}/dead-letter",
            post(whatsapp::post_whatsapp_command_dead_letter),
        )
        .route("/api/v1/integrations/whatsapp/fixtures/accounts", post(whatsapp::post_whatsapp_fixture_account))
        .route("/api/v1/integrations/whatsapp/sessions", get(whatsapp::accounts::get_whatsapp_sessions))
        .route(
            "/api/v1/integrations/whatsapp/fixtures/messages",
            post(whatsapp::post_whatsapp_fixture_message),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/message-updates",
            post(whatsapp::post_whatsapp_fixture_message_update),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/message-deletes",
            post(whatsapp::post_whatsapp_fixture_message_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/receipts",
            post(whatsapp::post_whatsapp_fixture_receipt),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/dialogs",
            post(whatsapp::post_whatsapp_fixture_dialog),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/participants",
            post(whatsapp::post_whatsapp_fixture_participant),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/reactions",
            post(whatsapp::post_whatsapp_fixture_reaction),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/media",
            post(whatsapp::post_whatsapp_fixture_media),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/statuses",
            post(whatsapp::post_whatsapp_fixture_status),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/status-views",
            post(whatsapp::post_whatsapp_fixture_status_view),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/status-deletes",
            post(whatsapp::post_whatsapp_fixture_status_delete),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/presence",
            post(whatsapp::post_whatsapp_fixture_presence),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/calls",
            post(whatsapp::post_whatsapp_fixture_call),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/runtime-events",
            post(whatsapp::post_whatsapp_fixture_runtime_event),
        )
        .route(
            "/api/v1/integrations/whatsapp/fixtures/sessions/authorized",
            post(whatsapp::post_whatsapp_fixture_authorized_session),
        )
}
