//! Managed Communications runtime contracts.

pub mod admission;
mod ai_source;
pub mod attachment_observation_consumer;
pub mod attachment_safety;
pub mod call_evidence_client_port;
pub mod call_evidence_consumer;
pub mod call_evidence_query_port;
mod call_evidence_realtime;
pub mod canonical_outbox;
pub mod canonical_read_cursor;
pub mod client_port;
pub mod consumer;
pub mod content_blob_client_port;
pub mod content_ticket_client_port;
pub mod content_ticket_store;
pub mod cross_channel_forward_source;
pub mod custody_worker;
pub mod domain_outbox;
pub mod event_runtime;
pub mod evidence_export_source;
mod explanation_source;
pub mod query;
pub mod query_client_port;
pub mod query_module_port;
pub mod query_port;
mod recipient_source;
pub mod saved_search_port;
pub mod search_access;
pub mod search_digest;
pub mod search_job;
pub mod search_projection;
pub mod search_query;
pub mod search_worker;
pub mod sender_insights_port;
pub mod storage_bundle;
mod summary_source;
mod translation_source;
