use crate::app::handlers::signal_hub::*;
use crate::app::state::AppState;
use axum::Router;
use axum::routing::{get, patch, post};

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route("/api/v1/signal-hub/sources", get(get_signal_hub_sources))
        .route(
            "/api/v1/signal-hub/sources/{source_code}",
            get(get_signal_hub_source),
        )
        .route(
            "/api/v1/signal-hub/capabilities",
            get(get_signal_hub_capabilities),
        )
        .route(
            "/api/v1/signal-hub/sources/{source_code}/enable",
            post(post_signal_hub_enable_source),
        )
        .route(
            "/api/v1/signal-hub/sources/{source_code}/disable",
            post(post_signal_hub_disable_source),
        )
        .route(
            "/api/v1/signal-hub/profiles",
            get(get_signal_hub_profiles).post(post_signal_hub_profile),
        )
        .route(
            "/api/v1/signal-hub/profiles/{profile_code}/apply",
            post(post_signal_hub_apply_profile),
        )
        .route(
            "/api/v1/signal-hub/profiles/{profile_code}",
            patch(patch_signal_hub_profile).delete(delete_signal_hub_profile),
        )
        .route(
            "/api/v1/signal-hub/connections",
            get(get_signal_hub_connections).post(post_signal_hub_connection),
        )
        .route(
            "/api/v1/signal-hub/connections/{connection_id}",
            patch(patch_signal_hub_connection).delete(delete_signal_hub_connection),
        )
        .route(
            "/api/v1/signal-hub/runtimes",
            get(get_signal_hub_runtime_states).post(post_signal_hub_runtime_state),
        )
        .route(
            "/api/v1/signal-hub/health",
            get(get_signal_hub_health).post(post_signal_hub_health_check),
        )
        .route(
            "/api/v1/signal-hub/replay",
            get(get_signal_hub_replay_requests).post(post_signal_hub_replay_request),
        )
        .route(
            "/api/v1/signal-hub/policies",
            get(get_signal_hub_policies).post(post_signal_hub_policy),
        )
        .route(
            "/api/v1/signal-hub/signals/mute",
            post(post_signal_hub_mute_signals),
        )
        .route(
            "/api/v1/signal-hub/signals/unmute",
            post(post_signal_hub_unmute_signals),
        )
        .route(
            "/api/v1/signal-hub/signals/pause",
            post(post_signal_hub_pause_signals),
        )
        .route(
            "/api/v1/signal-hub/signals/resume",
            post(post_signal_hub_resume_signals),
        )
        .route(
            "/api/v1/signal-hub/fixtures/system/restore",
            post(post_signal_hub_restore_system_fixture),
        )
        .route(
            "/api/v1/signal-hub/fixtures",
            get(get_signal_hub_fixture_sources),
        )
        .route(
            "/api/v1/signal-hub/fixtures/{fixture_id}/emit",
            post(post_signal_hub_emit_fixture_signal),
        )
}
