import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

describe('Telegram messenger action boundary', () => {
  it('keeps provider commands in app composition while Communications renders the working controls', () => {
    const appRoot = source('../../../../app/layout/AppLayoutRoot.vue')
    const appRunner = source('../../../../app/queries/useTelegramConversationRuntimeActions.ts')
    const runtimePanel = source('../../../../integrations/telegram/components/TelegramRuntimePanel.vue')
    const workspaceView = source('../../views/CommunicationsWorkspaceView.vue')
    const workspaceSurface = source('../../queries/useCommunicationsWorkspaceViewSurface.ts')
    const action = source('./MessengerAction.vue')
    const conversationInspector = source('./TelegramConversationInspector.vue')
    const messageInspector = source('./TelegramMessageInspector.vue')
    const viewer = source('./MessengerViewer.vue')
    const composer = source('./messengerComposer.ts')

    expect(appRoot).toContain('useTelegramConversationRuntimeActions')
    expect(appRoot).not.toContain('TelegramRuntimePanel')
    expect(appRoot).toContain(':telegram-runtime-action-runner="telegramRuntimeActions.run"')
    expect(appRunner).toContain("useMarkReadTelegramChatMutation")
    expect(appRunner).toContain("useTelegramMediaUploadMutation")
    expect(appRunner).toContain("queryKey: ['communications', 'telegram']")
    expect(runtimePanel).toContain('useTelegramRuntimePanelSurface')
    expect(runtimePanel).toContain('useTelegramCommandsQuery')
    expect(runtimePanel).toContain('useTelegramCallTranscriptQuery')
    expect(runtimePanel).toContain('useTelegramSendDryRunMutation')
    expect(runtimePanel).toContain('useTelegramProviderSearchMutation')
    expect(runtimePanel).toContain('useSetupTelegramAccountMutation')
    expect(runtimePanel).toContain('useLogoutTelegramAccountMutation')
    expect(runtimePanel).toContain('useRemoveTelegramAccountMutation')

    expect(workspaceView).toContain('telegramRuntimeActionRunner')
    expect(workspaceView).toContain('@conversation-action="surface.runTelegramConversationAction')
    expect(workspaceView).toContain("'upload_media'")
    expect(workspaceView).toContain('@download-attachment="surface.downloadTelegramAttachment')
    expect(workspaceSurface).toContain('useSendTelegramMessageMutation')
    expect(workspaceSurface).toContain('refreshTelegramConversations')
    expect(workspaceSurface).toContain('isTelegramConversationActionRunning')
    expect(workspaceSurface).toContain('createTelegramInitialHistorySynchronizer')
    expect(workspaceSurface).toContain('downloadTelegramAttachment')
    expect(workspaceView).toContain('@refresh="surface.refreshTelegramConversations"')
    expect(viewer).not.toContain('TelegramRuntimePanel')
    expect(workspaceSurface).toContain('TelegramConversationRuntimeActionRunner')
    const forbiddenIntegrationImport = `${['f', 'r', 'o', 'm'].join('')} '../../../integrations/telegram`
    expect(workspaceSurface).not.toContain(forbiddenIntegrationImport)

    expect(action).toContain("'mark_read'")
    expect(action).toContain("'sync_latest'")
    expect(action).toContain("'unarchive'")
    expect(action).not.toContain("AI Reply")
    expect(viewer).toContain("capability.id === 'telegram-file'")
    expect(viewer).toContain('pendingAttachment')
    expect(viewer).toContain("'download-attachment'")
    expect(viewer).toContain('() => props.conversation.id')
    expect(viewer).toContain('@submit="handleComposerSubmit"')
    expect(viewer).not.toContain("emit('upload-file', file, '')")
    expect(composer).toContain("id: 'telegram-file'")
    expect(composer).toContain('Voice, polls, scheduling and hidden-send options are not provider capabilities yet.')
    expect(conversationInspector).toContain('useCreateTelegramTopicMutation')
    expect(conversationInspector).toContain('useCloseTelegramTopicMutation')
    expect(conversationInspector).toContain('useTelegramChatFoldersQuery')
    expect(conversationInspector).toContain('Telegram folders')
    expect(conversationInspector).not.toContain('Provider folder id')
    expect(conversationInspector).toContain("runAction('download_media'")
    expect(messageInspector).toContain('useAddTelegramReactionMutation')
    expect(messageInspector).toContain('useRemoveTelegramReactionMutation')
    expect(messageInspector).toContain('useTelegramChatsQuery')
    expect(messageInspector).toContain('Forward to')
    expect(messageInspector).not.toContain('Forward to provider chat id')
    expect(messageInspector).not.toContain('Your Telegram sender id')
    expect(messageInspector).toContain("window.confirm('Delete this Telegram message from the provider?')")
  })
})
